tweag/asterius

asterius/app/ahc-ar.hs, asterius/app/ahc-ld.hs, asterius/app/ahc-pkg.hs, asterius/boot-init.sh, asterius/boot.sh, asterius/package.yaml, asterius/src/Asterius/Ar.hs, asterius/src/Asterius/Boot.hs, asterius/src/Asterius/BuildInfo.hs, asterius/src/Asterius/FrontendPlugin.hs, asterius/src/Asterius/Internals.hs, asterius/src/Asterius/Internals/Temp.hs, asterius/src/Asterius/Ld.hs, asterius/src/Asterius/Main.hs, asterius/src/Asterius/Store.hs, ghc-toolkit/src/Language/Haskell/GHC/Toolkit/FakeGHC.hs, ghc-toolkit/src/Language/Haskell/GHC/Toolkit/FrontendPlugin.hs, ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Run.hs
We'll implement `ahc-ld` & other related tools to link wasm objects & libs into final "executables".
=> Implement `ahc-ld`

asterius/test/array/.gitignore, asterius/test/bigint/.gitignore, asterius/test/bytearray/.gitignore, asterius/test/cloudflare/.gitignore, asterius/test/fib/.gitignore, asterius/test/jsffi/.gitignore, asterius/test/node-compile/.gitignore, asterius/test/rtsapi/.gitignore, asterius/test/stableptr/.gitignore, asterius/test/teletype/.gitignore, asterius/test/todomvc/.gitignore
This make git status way more pleasant to use after running the test
suite.
=> Add gitignores to all test folders

.ghcid, docs/hacking.md, mkdocs.yml
Add a hacking guide to help new contributors set up their workflow on hacking asterius.
=> Add a hacking guide

asterius/src/Asterius/Builtins.hs, asterius/test/fib/fib.hs
This PR implements `performMajorGC`/`performGC` in `System.Mem`.
=> Fix `performMajorGC`/`performGC`

asterius/rts/rts.float.mjs, asterius/rts/rts.mjs, asterius/src/Asterius/Builtins.hs
Currently experimenting with implementing the very bitfiddly `decodeFloat` function inside the RTS
=> Implement cbits/primFloat.c + some STG helpers for floats in GHC-testsuite

asterius/rts/rts.memory.mjs, asterius/rts/rts.messages.mjs, asterius/rts/rts.mjs, asterius/src/Asterius/Builtins.hs, asterius/test/fib/fib.hs
This PR depends on #133, so the history is understandably messy
=> Implement support for Debug.Trace.trace

.circleci/config.yml
- This is implemented on top of #159 , #157 , #158
=> [WIP] Add functionality needed for numrun014 to pass

asterius/test/ghc-testsuite.hs
GHC's testsuite does this, and we should follow suit.
Fixes #162
=> Teach ghc-testsuite to append trailing newline.

.circleci/config.yml, asterius/package.yaml, asterius/rts/rts.integer.mjs, asterius/test/largenum.hs, asterius/test/largenum/largenum.hs, ghc-toolkit/boot-libs/integer-simple/GHC/Integer/Type.hs
=> [WIP] Break number into 2 32 bits to prevent overflow when number is > MAX_SAFE_INTEGER (2^52)

.circleci/config.yml, asterius/src/Asterius/CodeGen.hs
Closed #161 in favor of this PR
=> Fix carry overflow

asterius/rts/rts.gc.mjs
=> Remove redundant IND scavenging branch

.circleci/config.yml
It seems CircleCI stopped offering xlarge resource class to us.
=> Use medium resource class on CircleCI

README.md, docs/building.md, docs/custom-ghc.md, docs/wasm-experimental.md, stack.yaml
Updates ghc (still on 8.6.5 but added new commits); corrects some outdated links and descriptions in readme/docs.
=> Misc updates

stack.yaml
This patch makes ``stack build`` works without messing with PATH
=> Stack: use ghc-variant

asterius/src/Asterius/CodeGen.hs, asterius/src/Asterius/Main.hs
Fix compilation warnings and browser warning about HTML encoding.
=> Fix some warnings

docs/index.md, docs/overview.md, docs/pipeline.svg
I've drawn the Asterius pipeline (as far as I understand it currently) and added it to the documentation. Please check that I didn't get anything wrong.
=> Add pipeline overview [skip ci]

ghc-toolkit/boot-libs/ghci/Asterius/GHCi.hs, ghc-toolkit/boot-libs/ghci/GHCi/InfoTable.hsc, ghc-toolkit/boot-libs/ghci/GHCi/Message.hs, ghc-toolkit/boot-libs/ghci/GHCi/Run.hs
This PR updates the `ghci` package to match the source code in our ghc fork, and also includes a prototypical implementation of ghci runner used by our current TH branch.
Note that #306 is the prequel of this PR; only merge before the prequel is merged.
=> Update the ghci boot lib to include the prototype asterius ghci runner

asterius/src/Asterius/CodeGen.hs, asterius/src/Asterius/EDSL.hs
Fix cgrun071 and cgrun077 in ghc-testsuite
=> Implement PopCnt, Clz and Ctz for W8, W16 and W32

ghc-toolkit/boot-libs/rts/Exception.cmm, ghc-toolkit/boot-libs/rts/PrimOps.cmm, ghc-toolkit/ghc-libdir/include/rts/storage/TSO.h, ghc-toolkit/package.yaml
Reintroduce the original RTS Cmm code and use CPP for Asterius specific changes (fix #308)
=> Reintroduce upstream RTS code (#308)

asterius/src/Asterius/Foreign.hs, asterius/src/Asterius/Foreign/Internals.hs
This PR belongs to a series of PRs to split up #321; comes after #322 
This PR implements two changes:
* In `Asterius.Foreign.Internal`, we implement `isJSValTy`, which tells if a `GHC.Type` is `JSVal`. We match the `UnitId`, `ModuleName` and `OccName`. It checks the *future* version of `JSVal`, which should be defined in `Asterius.Prim` in `ghc-prim`. Changes to the current `JSVal` will go in future PRs.
* In `Asterius.Foreign`, we change our FFI typecheck/desugar hook code and support `Any` and future `JSVal` as FFI import/export argument/result types. `Any` will be used for passing closure addresses of boxed types.
=> `Any` and new `JSVal` as FFI types

ghc-toolkit/src/Language/Haskell/GHC/Toolkit/FakeGHC.hs
Related: #342 
For now, producing an ELF "executable" with wasm stuff is too much work, especially given the constraint of not patching Cabal. Here we do a workaround: when we detect the output path is something like `../dist/setup/setup`, we short-circuit `ahc` logic and call `ghc` to produce the executable, with the original ghc global pkgdb.
My eyes are bleeding with this hack. But at least it works to make `singletons` properly (?) pass the configure step and kick off building. And maybe for other packages out there as well, iff their custom `Setup.hs` doesn't have any `setup-deps` outside the ghc global pkgdb.
=> Workaround lack of custom `Setup.hs` support

asterius/src/Asterius/Foreign/Internals.hs
When working on #347 we discovered that the logic to parse GHC FFI type signatures didn't handle the case when type variables are present (e.g. `Ptr a`), and would simply fail with a pattern match error. This PR drops top-level `forall`s when parsing JSFFI signatures to fix the problem; also, when the parsing fails, we now output more informative error message including the failed type signature.
=> Fix JSFFI signatures with type variables

.circleci/config.yml, asterius/rts/rts.gc.mjs
=> Fix regression in yolo mode

asterius/rts/rts.gc.mjs
The change in PR #424 actually introduced a bug: for instance, the packages `contravariant-extras` and `cql` do not build anymore, getting an "Invalid live mblock" error such as:
```
RuntimeError: RuntimeError: Invalid live mblock 0x1ffff700100100
at HeapAlloc.handleLiveness (file:///home/asterius/.asterius/.stack-work/install/x86_64-linux-custom-asterius-tinfo6/a6f37316a3da926688ff81f5b3da56a72cf3b7b83dd723525b6931d11f77da34/8.6.5/share/x86_64-linux-ghc-8.6.5/asterius-0.0.1/rts/rts.heapalloc.mjs:172:15)
at GC.performGC (file:///home/asterius/.asterius/.stack-work/install/x86_64-linux-custom-asterius-tinfo6/a6f37316a3da926688ff81f5b3da56a72cf3b7b83dd723525b6931d11f77da34/8.6.5/share/x86_64-linux-ghc-8.6.5/asterius-0.0.1/rts/rts.gc.mjs:863:20)
at Scheduler.returnedFromTSO …
```
=> Bugfix - Use forwarding pointers during GC 

asterius/app/ahc-ld.hs
#445 didn't work. Now it does.
=> Fix #445 regression

asterius/rts/rts.gc.mjs
=> Fix number conversion error in GC

asterius/src/Asterius/CodeGen.hs
This PR adds support for `"dynamic"` targets of `foreign import ccall`. Although this doesn't sound like something to be useful in a haskell-to-web scenario, it fixes an example involving `ghc-lib-parser`.
=> Handle dynamic ccall targets

asterius/rts/rts.float.mjs, asterius/rts/rts.time.mjs
Just a couple of tiny bugfixes (spotted by chance by running Google's closure compile on the RTS).
=> Misc small bug-fixes

asterius/rts/rts.gc.mjs
The PR #439 implemented selector optimisation during GC, but it also included a few bugs that went undetected (mainly because the optimisation is never really performed by the tests in `ghc-testsuite`, and also because we were not able to create artificial unit tests that covered the whole code).
The cause for the errors was basically in a few pointers that were not dereferenced correctly, an issue in the selection itself, and the incomplete handling of all constructor closure types (`CONSTR`, `CONSTR_i_j`, `CONSTR_NOCAF`).
This PR also provides more comments, and a refactoring that uses locally defined variables, so to avoid a previous bug due to variable shadowing.
**Note.** The `stingyEval` function, which performs the optimisation, is a non-trivial function that keeps a stack of …
=> Fix Selector Optimisation, pt. II

ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Hooks.hs
Should fasten the GHC hooks in `ghc-toolkit` a bit.
* Previously, we had a "duplicate check" which prevents running the `Compiler` twice on the same module. Back then we didn't know the duplication was caused by `-dynamic-too` in GHC, which runs the pipeline twice. Now we forbid dynamic object generation during booting and in `ahc-cabal`, so this check isn't necessary anymore.
* We use `ModuleEnv` for the `Module` mapping, and switch away from `MVar` to lighterweight `IORef`s for the global mapping, since the critical section should be pretty short and not worth a context switch in most cases.
=> Fasten the GHC hooks

asterius/app/ahc-dist.hs, asterius/src/Asterius/Ar.hs, asterius/src/Asterius/Backends/Binaryen.hs, asterius/src/Asterius/Boot.hs, asterius/src/Asterius/Builtins.hs, asterius/src/Asterius/CodeGen.hs, asterius/src/Asterius/Internals.hs, asterius/src/Asterius/JSFFI.hs, asterius/src/Asterius/Ld.hs, asterius/src/Asterius/Main.hs, asterius/src/Asterius/Resolve.hs, asterius/src/Asterius/TypesConv.hs, asterius/test/node-compile.hs
This addresses https://github.com/tweag/asterius/issues/514.
=> Replace Asterius.Internals.IO with GHC.Types.IO

asterius/src/Asterius/Backends/Binaryen.hs, asterius/src/Asterius/Main.hs
Main changes in this PR: some logic has been moved from `Asterius.Main` to the `binaryen` backend.
* After we call `c_BinaryenModuleCreate` and get a `BinaryenModuleRef`, we immediately set the module features with `c_BinaryenModuleSetFeatures` before performing any marshaling logic. It's possible that in the future versions of `binaryen`, the C API may error when trying to add an opcode that doesn't belong to a `BinaryenModuleRef`'s feature set. So the feature set should be assigned in the beginning.
* Before `marshalModule` returns the resulting `BinaryenModuleRef`, we run the `limit-segments` pass to limit the data segments count. This happens before any optimization/shrinking passes are run since `limit-segments` is mandatory and later passes shouldn't affect the segment count anyway. …
=> Minor tweaks in the `binaryen` backend

.circleci/config.yml, asterius/src/Asterius/Backends/WasmToolkit.hs
- Address issue https://github.com/tweag/asterius/issues/522
- Some haddock-compatible comments
- Other minor refactorings
=> Improvements in Asterius.Backends.WasmToolkit

.github/settings.yml
Sync with version of `settings.yaml` in tweag/guides.
=> Update GitHub settings: label descriptions

README.md, docs/hacking.md, utils/ghcid.sh, utils/readme.md
This is mainly a documentation improvement PR.
* Added a section explaining VSCode remote container.
* Added a section about building profiled `asterius`.
* Other minor improvements.
=> Improve the hacking guide

asterius/src/Asterius/Builtins.hs, asterius/src/Asterius/CodeGen.hs, asterius/src/Asterius/Foreign/Internals.hs, asterius/src/Asterius/FrontendPlugin.hs, asterius/src/Asterius/JSFFI.hs, asterius/src/Asterius/Types.hs, asterius/src/Asterius/TypesConv.hs
Closes https://github.com/tweag/asterius/issues/565.
=> WIP Fix Issue #565

.buildkite/Setup.hs, .buildkite/pipeline.yml, .buildkite/profile.sh, docs/hacking.md, lts-profile.sh, profile.Dockerfile
This PR implements:
* `profile.Dockerfile` which does a profiled build of `asterius`
* The documentation of using `profile.Dockerfile` to perform profiling
* A new CI job `asterius-profile` which links a large program and uploads the profile reports as artifacts
=> Run profiled build on CI

asterius/src/Asterius/Backends/Binaryen.hs, asterius/src/Asterius/Backends/WasmToolkit.hs, asterius/src/Asterius/Resolve.hs, asterius/src/Asterius/Types.hs
=> [WIP] Remove Memory/Table exports

asterius/src/Asterius/Backends/Binaryen.hs, asterius/src/Asterius/Backends/WasmToolkit.hs, asterius/src/Asterius/TypeInfer.hs, asterius/src/Asterius/Types.hs
=> [WIP] Remove Host and HostOp

asterius/src/Asterius/GHCi/Internals.hs, ghc-toolkit/boot-libs/ghci/Asterius/GHCi.hs
Previously, our TH runner doesn't properly pass the `Loc` info from the host GHC process to the `node` process. As a result, the `qLoc` interface doesn't work. Fixing this makes us a lot closer to getting more TH splices to be supported (especially for `singletons`, although it fails for another rts-related reason for now).
=> Fix missing `Loc` info in TH runner

asterius/src/Asterius/CodeGen.hs, asterius/src/Asterius/Passes/Relooper.hs, asterius/src/Asterius/Types.hs
This PR closes https://github.com/tweag/asterius/issues/592.
=> Improve Asterius.CodeGen

lts.sh
Adds known-to-build packages in `lts-15.10`.
=> Adjust image build script

asterius/src/Asterius/Builtins.hs, asterius/src/Asterius/Builtins/Sparks.hs
=> No-op par# and spark#

asterius/app/ahc-cabal.hs, asterius/app/ahc.hs, asterius/src/Asterius/Internals/Temp.hs, asterius/test/ghc-testsuite.hs
Just tiny things I came across while browsing the code.
=> Minor refactoring and some comments

asterius/src/Asterius/Builtins/Malloc.hs
Closes https://github.com/tweag/asterius/issues/672.
=> Implementation of calloc, using malloc and memset

asterius/src/Asterius/Backends/Binaryen.hs, asterius/src/Asterius/Internals/Arena.hs, asterius/src/Asterius/Internals/Marshal.hs, asterius/src/Asterius/Main.hs
=> Use arena allocation for the binaryen backend

asterius/boot.sh
Today's machines are multicore, use them!
=> Build w/ parallelism

asterius/src/Asterius/Types.hs
When loading object files (in Asterius.Ar.loadArchive and Asterius.Ld.loadTheWorld) we silently ignore malformed object files, which likely come from gcc-compiled files in libraries. Adding a magic string at the beginning of each object file should speed things up a little, since we can detect such deserialization failures faster.
=> Prefix object files with a "magic" string for faster failure

asterius/src/Asterius/Backends/Binaryen.hs, asterius/src/Asterius/Backends/WasmToolkit.hs, asterius/src/Asterius/Builtins.hs, asterius/src/Asterius/Foreign/DsForeign.hs, asterius/src/Asterius/Passes/GCSections.hs, asterius/src/Asterius/Resolve.hs, asterius/src/Asterius/TypeInfer.hs, asterius/src/Asterius/Types.hs
This PR shall add support for global variables in Asterius' PR. Currently work in progress.
=> Add IR support for Wasm globals

asterius/src/Asterius/Main.hs
Factored out from  #737.
Previously, all platform-specific rts logic needs to be put into `default.mjs`, and cross-referencing between them and platform-independent rts don't work well due to directory mismatch. Now, we just copy all files in `node`/`browser` to the build target directory. Assuming `node`/`browser` scripts export the same classes from the same files, `rts.mjs` and other platform-independent rts can import them just fine.
=> Allow multiple scripts in platform-specific rts

asterius/rts/rts.mjs, asterius/rts/rts.scheduler.mjs
=> Remove redundant fs dependency in scheduler

asterius/rts/browser/default.mjs, asterius/rts/browser/rts.fs.mjs, asterius/rts/node/default.mjs, asterius/rts/node/rts.fs.mjs, asterius/rts/rts.messages.mjs, asterius/rts/rts.mjs, asterius/rts/rts.node.mjs, asterius/src/Asterius/GHCi/Internals.hs, asterius/src/Asterius/JSRun/Main.hs, asterius/src/Asterius/JSRun/NonMain.hs, asterius/src/Asterius/Main.hs
=> Reimplement FS read/write

asterius/src/Asterius/Backends/Binaryen.hs, asterius/src/Asterius/Backends/WasmToolkit.hs, asterius/src/Asterius/Main.hs
=> Disentangle the data/function symbol maps in the backends

.github/workflows/setup-deps.sh, stack-profile.yaml, stack.yaml
Following the upgrade in Debian sid repo.
=> Update binaryen and use version_96

.github/workflows/setup-deps.sh, base.Dockerfile, dev.Dockerfile, dev.rootless.Dockerfile, stack-profile.yaml, stack.yaml
* Use binaryen version 99
* Mitigate WebAssembly/binaryen#3481
* Update Haskell bindings to `binaryen-0.0.6.0`
=> Use binaryen version 99

.github/workflows/setup-deps.sh, base.Dockerfile, dev.Dockerfile, dev.rootless.Dockerfile
The fix has already been included in the Debian package repo.
=> Remove binaryen 3481 hack

docs/src/SUMMARY.md, docs/src/milestones-2022-01.md, docs/src/scheduler.md, docs/src/semantics.md
This PR contains planning work that @TerrorJack and @nrnrnr have been doing.
=> in-migrate work on milestones, concurrency, foreign calls

docs/src/SUMMARY.md
=> placate mdbook
