- .circleci/build.mk
- .circleci/config.yml
- .gitmodules
Key points:
* Keep `ghc` in the repo using git submodules.
* Compile `ghc` with custom config as part of Asterius CI.
* Cache the result and avoid re-compiling GHC unless necessary.
* Pushing to gh pages happens as a separate job using CircleCI workflows and via SSH avoiding compromising GH token.
> Improve CircleCI script

- binaryen/Setup.hs
- binaryen/package.yaml
The ar on macOS ships without support for MRI scripts, and it is
non-trivial to obtain a proper copy on macOS.  Instead we now just
use the Ar support that's in GHC for the precisly same reason.
We'll special case macOS here, as gnu ar is supposed to work on
windows and linux.
> Work around the lack of -M on macOS for ar

- asterius/src/Asterius/FrontendPlugin.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/FakeGHC.hs
Goal: `ahc` is our `ghc` wrapper executable which works only when invoked from the boot script. We shall make it accept user code as well, so `ahc --make Foo.hs` will work the same way as compiling boot libs. As for linking & stub generation, those logic used to belong to `ahc-link` and will stay there for a while.
> Make `ahc` accept user code

- asterius/src/Asterius/Boot.hs
- asterius/src/Asterius/FrontendPlugin.hs
- asterius/src/Asterius/Main.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Compiler.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/FakeGHC.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Hooks.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Run.hs
We're replacing `.o` host object files generated from gcc assembler with our custom ones. For library targets, they will get bundled by `ar` and copied to the destination pkgdb by Cabal.
After this is implemented, at link time, we can seek to deprecate the global "store" mechanism and use those `.a` archives instead.
> Replace host object files with wasm ones

- asterius/app/ahc-ar.hs
- asterius/boot-init.sh
- asterius/package.yaml
- asterius/src/Asterius/Ar.hs
- asterius/src/Asterius/Boot.hs
- asterius/src/Asterius/BuildInfo.hs
- asterius/src/Asterius/CodeGen.hs
- asterius/src/Asterius/FrontendPlugin.hs
- asterius/src/Asterius/Main.hs
- asterius/src/Asterius/Types.hs
Previously in #63, we made `ahc` generate `.o` wasm object files which are bundled by gnu ar and copied by Cabal. Now we'll implement `ahc-ar` and other necessary utilities to:
* Add symbol indices into `.a` archives
* Reconstruct stores from archives, without losing lazy loading of individual object files
* Get rid of the legacy object storage completely.
> Implement `ahc-ar`

- asterius/rts/rts.fs.mjs
Closes #59
currently `NodeFileSystem` is not used, so it can be dropped for now instead of breaking `--browser` compatibility.
> Remove NodeFileSystem and unwanted dependency

- .circleci/config.yml
- Dockerfile
- README.md
- asterius/app/ahc-cabal.hs
- asterius/package.yaml
- docs/ahc-link.md
- mkdocs.yml
So, finally here we are. `ahc-cabal` is the wrapper executable for `cabal`, so users won't need to pass a bunch of specific configure flags in order to make `ahc` and its friends work out of the box.
> Implement ahc-cabal

- asterius/src/Asterius/Main.hs
Example `jsffi.mjs` is now rendered as when `--sync` option is passed.
```
import {module} from "./jsffi.wasm.mjs";
import * as jsffi from "./jsffi.lib.mjs";
process.on("unhandledRejection", err => { throw err; });
let i = jsffi.newInstance(module);
try {
i.wasmInstance.exports.hs_init();
if (i.wasmInstance.exports.main)
i.wasmInstance.exports.main();
} catch (err) {
console.log(i.stdio.stdout());
throw err;
}
console.log(i.stdio.stdout());
export const putchar = i.wasmInstance.exports.putchar
export const mult_hs_double = i.wasmInstance.exports.mult_hs_double
export const mult_hs_int = i.wasmInstance.exports.mult_hs_int
```
It allows test case to be invoked like.
```
import {mult_hs_int, mult_hs_double, putchar} from './jsffi.mjs';
console.log(mult_hs_int(9,9)); …
```
> Add exports and conditional main execution for --sync target

- asterius/src/Asterius/Internals.hs
- asterius/src/Asterius/Main.hs
- asterius/src/Asterius/Resolve.hs
- docs/ahc-link.md
Relevant: #51
This PR speeds up `mergeSymbols`, where we perform dependency analysis and discover live code.
Note that we also removed the ability to output symbol dependency graph as a GraphViz file. Use cases are extremely rare anyway.
> Faster dependency analysis

- stack.yaml
Relevant: #54 
`HscMain.doCodeGen` is not exposed in upstream ghc. This updates the ghc bindists to include the necessary change for implementing the Core -> Wasm hook in TH support.
> Update ghc to expose HscMain.doCodeGen in ghc api

- asterius/app/ahc-ar.hs
- asterius/src/Asterius/Ar.hs
- asterius/src/Asterius/JSFFI.hs
- asterius/src/Asterius/Main.hs
- asterius/src/Asterius/Passes/DataSymbolTable.hs
- asterius/src/Asterius/Resolve.hs
- asterius/src/Asterius/Types.hs
Besides tracking liveness of data segments and functions, the linker also tracks JSFFI imports/exports. Previously, when chasing dependencies, whenever a module was touched, all its JSFFI declarations are included. This is a simple coarse-grained approach proved to work.
Recently we did quite some improvements in the linker (#84) and as a result, all JSFFI declarations of every single module in boot libs and user code is included, which bloats the import/export sections of wasm code and the companion js module. This PR properly implements the filter to exclude unneeded JSFFI declarations from the linker result.
> Track JSFFI imports/exports in dependency analyzer

- asterius/src/Asterius/Passes/All.hs
- asterius/src/Asterius/Passes/MergeSymbolOffset.hs
This PR adds a rewriting pass for load/store instructions: when the address is a symbol (with offset), we set the symbol offset to 0 and merge it into the outer load/store offset. This improves debug logs since more symbols can be re-discovered when looking up a base address in the symbol table.
> Wip merge symbol offset

- asterius/rts/rts.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Main.hs
- asterius/src/Asterius/Marshal.hs
- asterius/src/Asterius/NewMarshal.hs
- asterius/src/Asterius/Passes/FunctionSymbolTable.hs
- asterius/src/Asterius/Resolve.hs
- asterius/src/Asterius/Types.hs
- binaryen/binaryen/src/binaryen-c.cpp
- binaryen/binaryen/src/binaryen-c.h
- binaryen/src/Bindings/Binaryen/Raw.hs
Relevant: #54 
Like #90, but done for tables. Also removed a previous binaryen hack and fixed binaryen validation.
Besides the need of dynamic linking from TH/GHCi, an additional benefit for importing table from js: it's easier to play with wasm's reference types proposal; we only need to set `{element: "anyref"}` when creating a table in js, without changing wasm-toolkit/binaryen logic. This is already supported in recent V8 revisions.
> Use imported table for asterius instances

- binaryen/Setup.hs
- binaryen/package.yaml
This PR extends #55 to improve `binaryen` build script, uniformly uses `Ar` instead of `ar -M` on all platforms. Also gets rid of CPP usage in `Setup.hs` and solves a Cabal warning on non-macOS platforms.
> Uniform `binaryen` build script for all platforms

- .circleci/config.yml
- asterius/app/ahc-ld.hs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Internals/MagicNumber.hs
- asterius/src/Asterius/Ld.hs
- asterius/src/Asterius/Main.hs
- asterius/src/Asterius/Passes/DataSymbolTable.hs
- asterius/src/Asterius/Passes/GlobalRegs.hs
- asterius/src/Asterius/Resolve.hs
- docs/ahc-link.md
Relevant: #54 
This PR adds a `--no-gc-sections` switch to `ahc-link`/`ahc-ld` which makes it possible to switch off dead code elimination. This is beneficial for our current work in TH.
Also fixes a previous bug which renders the bytestring cbits functions unusable due to conflicting import/wrapper symbol clashes.
> Make dead code elimination optional

- .circleci/config.yml
- README.md
- asterius/app/ahc-ld.hs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/CodeGen.hs
- asterius/src/Asterius/EDSL.hs
- asterius/src/Asterius/Internals.hs
- asterius/src/Asterius/Ld.hs
- asterius/src/Asterius/Main.hs
- asterius/src/Asterius/Marshal.hs
- asterius/src/Asterius/NewMarshal.hs
- asterius/src/Asterius/Passes/All.hs
- asterius/src/Asterius/Passes/LocalRegs.hs
- asterius/src/Asterius/Resolve.hs
- asterius/src/Asterius/Types.hs
- docs/ahc-link.md
- utils/v8-node.py
- wasm-toolkit/src/Language/WebAssembly/WireFormat.hs
We used to have `[] -> [i64]` sigs for wasm functions translated from a cmm graph. When tinkering on the linker and moving passes back to the codegen, I realized we can change them to `[] -> []`, and the return address can be passed via a global state instead. Benefits compared to the old way:
* We used to reserve a write-once local reg in every cmm function just for the return address. Which was a legacy hack and a waste (see below)
* We used to use the `binaryen` relooper, which easily breaks validation when the graph needs to return anything in an exit block. To workaround that we added a return address reg, make the graph write to that reg and return its content as function output, which (due to misdocumentation) triggered undefined behavior in `binaryen` and led to a long term …
> Change Cmm function sigs to `[] -> []` and implement tail call opcodes

- docs/jsffi.md
It was renamed here: https://github.com/tweag/asterius/commit/468e87fad60129377e1ea19b40eaae006e7d1495#diff-ea79f4a631729e3328429d30a211e065R594
> :memo: Fix: FFI_JSREF -> FFI_JSVAL

- asterius/rts/rts.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/test/fib/fib.hs
This was more to understand the codebase. But if this is useful, we can use this to add checking
for equality / inequality quite easily.
> Add new intrinsic assertEqI64 to check if two I64s are equal.

- asterius/test/fib/fib.hs
First add `assert_eq_i64 10 10` to check that `asseet_eq_i64` succeeds when inputs are equal. We will add another test case to ensure that `assert_eq_i64` fails correctly when its inputs are not
equal.
Beef up the `fib.hs` test case by using `assert_eq_i64` wherever
appropriate to check for regression.
> Make fib.hs check for regression by using assert_eq_i64

- asterius/package.yaml
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/CodeGen.hs
- asterius/test/bytearray/bytearray.hs
- asterius/test/bytearraymini.hs
- asterius/test/bytearraymini/bytearraymini.hs
This PR supersedes #112. This is a cleaned up version of PR #112 with consistent history. 
We add a testcase `bytearraymini` which is a simplified version of `bytearray` which tests `I8/I16 -> I64` upcasting.
Unfortunately, we do not have a testcase for the downcast of `I64/I32 -> I16/I8`, though the code path has been implemented in the same test case.
> Correct MOD_SS_Conv/Mod_UU_Conv behaviour for I8/I16

- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/EDSL.hs
Closes some issues in meta-issue #46 
- Add some comments around `EDSL.hs` explaining some of the data structures
- change the signature of `runEDSL` to no longer require return types. Return types can be set using `setReturnTypes`. This reduces redundancy in the `EDSL`, and is also more in-like with its imperative nature.
> [WIP] Improving the EDSL interface - Part 1

- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/EDSL.hs
We achieve this by having `runEDSL` return an `AsteriusModule` instead of a `Function`. This allows us to 
provide primitives in the `EDSL` such as `declareStaticSymbol`. This would allow us to talk about such a symbol in the context of the function we are building. This helps improve cohesion --- we are declaring and using these static buffers at the same point, instead of declaring them at one place and using them at another.
We introduce `generateWrapperModule`, which wraps all functions in an entire module. This reduces duplication in comparison to the old implementation.
The diff is large since most of `Builtins.hs` uses `runEDSL`.
> [WIP] Change the EDSL API to allow declaring of static sections while building functions

- asterius/src/Asterius/Main.hs
Previously, we introduced an inline-js runner for wasm/js generated by `ahc-link`, and enabled it as the default when running `ahc-link --run` for inputs without custom entry module. However, in practice it seems the inline-js runner produces poorer error messages than the previous node runner.
Now, we still use the old node runner for all `ahc-link --run` calls, and the inline-js runner is still preserved in the `nomain` unit test & the experimental TH splice runner on the `wip-jsrun` branch.
> Fallback to the node runner in `ahc-link --run`

- .circleci/config.yml
- asterius/rts/rts.memory.mjs
- asterius/rts/rts.memorytrap.mjs
- asterius/rts/rts.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Main.hs
- asterius/src/Asterius/MemoryTrap.hs
- asterius/src/Asterius/Resolve.hs
- stack.yaml
In the previous efforts to make the linker faster, we moved the link-time rewriting passes to compile-time, and unfortunately dropped support for "memory trap" & "tracing" passes.
This PR reimplements the memory trap framework, enabled by the `--debug` flag of `ahc-link`/`ahc-dist`. Compared to the previous implementation, it:
* Relies on the `--experimental-wasm-bigint` V8 feature flag, and requires using V8 team's node integration build to run.
* The read/write barriers are solely implemented in JavaScript. The wasm load/store instructions are mapped 1-to-1 to calls of imported barrier functions. No intermediate wasm trap functions exist anymore.
* The trap is enabled for all wasm functions, even the built-in rts routines, since we don't need to worry about reentrancy issues.
* We also …
> Re-enable the memory trap framework of debug mode

- asterius/src/Asterius/Boot.hs
This PR removes ticks in pretty-printed IR dumps when `ASTERIUS_DEBUG=1` is set when calling `ahc-boot`, reducing a lot of visual noise. For the raw Cmm AST dump, however, we don't bother to filter out the `CmmTick` instructions yet.
> Suppress ticks in debug mode pretty-printed dumps

- .circleci/config.yml
- asterius/package.yaml
- asterius/rts/rts.exception.mjs
- asterius/rts/rts.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/JSGen/Constants.hs
- asterius/src/Asterius/Ld.hs
- asterius/src/Asterius/Main.hs
- asterius/test/exception.hs
- asterius/test/exception/exception.hs
- ghc-toolkit/cbits/ghc_constants.c
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Constants.hs
This PR implements the underlying rts routines for exception handling primops, so `throw`/`throwIO`/`catch` functions in `Control.Exception` now work. We include an example in the `exception` unit test.
Compared to "full" exception support in ghc rts:
* We don't consider the handling of async exceptions yet, not before we have an IO manager and threading support.
* We don't support STM-related exception handling yet.
* The `main` closure is not wrapped with `runMainIO`, so if the `main` function throws, we don't print the exception and exit as ghc rts does.
> Basic exception handling support

- asterius/rts/rts.exception.mjs
- asterius/rts/rts.mjs
- asterius/src/Asterius/Backends/Binaryen.hs
- asterius/src/Asterius/Backends/WasmToolkit.hs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Internals.hs
- asterius/src/Asterius/Internals/Barf.hs
- asterius/src/Asterius/Ld.hs
- asterius/src/Asterius/Resolve.hs
This PR implements the following mechanism:
* `barf()` as seen in ghc rts. Since we don't have varargs ABI yet, we restrict `barf()` to take exactly one pointer arg, and slice away other args (or provide a `0` in case there's none).
* When the linker sees an unresolved symbol, it dynamically adds an error string as a data segment into the resulting module.
* When the `wasm-toolkit`/`binaryen` backends see an unresolved symbol, they attempt to substitute it with a `barf()` call rather than a simple `unreachable` opcode.
When execution of wasm reaches an unresolved symbol, then the symbol will show up in the js error message.
> Report unresolved symbols in runtime error messages

- .circleci/config.yml
- asterius/test/group-common-tests-ghc-testsuite-report.py
This lets us estimate the impact of fixing a particular bug in terms
of number of tests that share the same error.
> Run helper script during CI to group tests by error

- asterius/src/Asterius/Builtins.hs
This PR fixes the `noDuplicate#` primop, making `unsafePerformIO` work. Also, `getNumCapabilities` is working.
> Fix noDuplicate#

- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Ld.hs
This PR fixes `System.Environment.getProgArgv`. Since `argv` makes little sense in a web setting, we hard-code it to contain exactly one C string, which is the program name taken from the `ahc-ld` output path.
Note that `getProgName` and `getArgs` still doesn't work yet, due to lack of `iconv`. That will be fixed in a subsequent PR.
> Fix getProgArgv

- asterius/src/Asterius/Builtins.hs
- asterius/test/fib/fib.hs
This PR fixes `foreign import ccall safe` by implementing no-op `suspendThread`/`resumeThread`.
The original versions of those two functions are based on `Capability`/`Task`/`InCall` data structures, and in our case, we don't have multi-threads yet, nor do we intend to implement threads with `Task`/`InCall`s, so it's safe to have no-op versions first.
When we later add multi-thread support, we'll revisit this ticket and have `suspendThread`/`resumeThread` collaborate with the new TSO manager.
> Fix "safe" ccalls

- asterius/src/Asterius/Builtins.hs
This PR fixes `localeEncoding` called by `iconvEncoding` in `GHC.IO.Encoding.Iconv`. `localeEncoding` always return `UTF-8` at the moment. After #133 is reviewed and merged as well, this will make functions like `withCString` work.
> Fix `localeEncoding`

- .circleci/config.yml
- asterius/rts/rts.mjs
- asterius/src/Asterius/JSGen/Wasm.hs
- asterius/src/Asterius/JSRun/NonMain.hs
- asterius/src/Asterius/Main.hs
- asterius/test/cloudflare.hs
- docs/ahc-link.md
This PR removes the "sync mode".
When we call `ahc-link`/`ahc-dist` with `--sync`, the resulting main js module performs WebAssembly compilation/instantiation synchronously. Back when we added this sync mode, its only intended use scenario is Cloudflare Workers: its runtime supports synchronous WebAssembly instantiation, and the fetch event handler must be already set up when the script finishes, thus we needed to synchronously return an asterius instance and call `hs_init`/`main` for proper event handling. We don't use "sync mode" in any other scenario, and synchronous WebAssembly compilation/instantiation is a known anti-pattern.
Right now, we've come to the point where asynchronous instantiation of the runtime is a must, and sync mode will cease to work, so we chop it off in this PR. …
> Remove "sync mode"

- asterius/rts/rts.exception.mjs
This PR fixes an error in `rts.exception.mjs` which breaks `RET_FUN` stack frame handling.
> Fix rts.exception.mjs

- asterius/rts/rts.mjs
Relevant: #77 
This PR cleans up the legacy code in `rts.mjs` related to the no-longer provided "vault" feature.
> Prune legacy rts code related to "vault"

- asterius/rts/rts.mjs
- asterius/rts/rts.threadpaused.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Ld.hs
This PR fixes the previously no-op `threadPaused`. We now properly traverse the stack and perform lazy blackholing for update frames.
> Fix threadPaused

- asterius/src/Asterius/Builtins.hs
A sequel to #138: we should call `threadPaused` in `suspendThread` since the calls to "safe" ccall imports should also be a gc safepoint.
> suspendThread should call threadPaused

- asterius/src/Asterius/Boot.hs
- asterius/src/Asterius/Internals/Directory.hs
It seems `cmm-sources` in `.cabal` files isn't working yet, and other boot libs may contain `.cmm` as well (`base` & `ghc-heap` at the moment), so here we are.
> Compile `.cmm` files in other boot libs

- asterius/package.yaml
- asterius/src/Asterius/Backends/Binaryen.hs
- asterius/src/Asterius/Main.hs
- asterius/src/Asterius/Types.hs
The `binaryen` package has a custom `Setup.hs` script to handle building/linking of `binaryen`, which can make things nasty and produce cryptic linker errors when building `asterius` in certain ways (e.g. with nix). Here we provide a `binaryen` Cabal flag for the `asterius` package which is on by default, but when switched off can disable the `binaryen` dependency of `asterius`.
> Provide a `binaryen` Cabal flag in the `asterius` package to disable the binaryen backend

- asterius/rts/rts.gc.mjs
- asterius/rts/rts.mjs
- asterius/rts/rts.reentrancy.mjs
- asterius/src/Asterius/Builtins.hs
Before more radical experiments regarding the FFI mechanism and scheduler, here we implement a simple reentrancy guard to ensure certain components of rts won't be reentered, and panics immediately otherwise. The guard is currently applied to two places: `gcRootTSO`, which is our gc entry function, and all `rts_eval*` functions, which creates a new thread and enters the scheduler to perform evaluation.
> Implement reentrancy guard

- .circleci/config.yml
- asterius/package.yaml
- asterius/rts/rts.md5.mjs
- asterius/rts/rts.memory.mjs
- asterius/rts/rts.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/test/sizeof_md5context.hs
- asterius/test/sizeof_md5context/sizeof_md5context.hs
- ghc-toolkit/boot-libs/base/GHC/Fingerprint.hs
We implement a simple hash function to allow `Data.Typeable` to get going, and anything that depends on `GHC.Fingerprint`, really.
We implement a simple `FNV` hash, and hope that this suffices for what we need.
This should fix (at least):
- `test/ghc-testsuite/codeGen/T5129.hs`
- `test/ghc-testsuite/numeric/numrun013.hs`
- `test/ghc-testsuite/deSugar/DsMultiWayIf.hs`
> implement FNV hash instead of MD5

- .circleci/config.yml
- asterius/rts/rts.float.mjs
- asterius/rts/rts.integer.mjs
- asterius/rts/rts.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/CodeGen.hs
- ghc-toolkit/boot-libs/integer-simple/GHC/Integer/Type.hs
This fixes double decoding, and implement various bits of the `float` RTS primitives that the test depends on.
@TerrorJack I propose that we teach CI about some ghc testsuite tests which we expect to pass from now on, so that these tests do not regress.
> Implement changes needed for `cgrun044` to pass

- asterius/test/ghc-testsuite.hs
GHC sometimes has tests for 64 and bit architectures which differ.
In asterius, we always want to pick up the 64 bit versions, so change
our test runner to do so.
> Add support for using the 64-bit testcases

- .circleci/config.yml
- asterius/rts/rts.float.mjs
- asterius/src/Asterius/Builtins.hs
Another one bites the dust of the newline issue:
- This is on top of #163, #165 
```
Progress 1/2: asterius-0.0.1asterius ghc-testsuite
test/ghc-testsuite/numeric/numrun016.hs
test/ghc-testsuite/numeric/numrun016.hs: FAIL (1.45s)
expected: "0.0 :+ 3.141592653589793\n0.0 :+ 3.1415927"
but got: "0.0 :+ 3.141592653589793\n0.0 :+ 3.1415927\n"
```
> implement isDoubleFinite/isFloatFinite: fix numrun016

- .circleci/config.yml
- asterius/test/format-ghc-testsuite-report.py
- asterius/test/group-common-tests-ghc-testsuite-report.py
This lets us:
- Be nice `*nix` citizens and just redirect / pipe their output
- Makes using them nicer during development. We no longer need to write
to a file and then `cat` the file. We can just call the tool against
the raw `test-report.csv` and see pretty-printed output.
It's a small workflow change that makes the script a little nicer to use.
> Make helper scripts dump directly to stdout

- .gitignore
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/FakeGHC.hs
After `stack` upgrades to 2, it seems that more ghc related environment variables are passed for various `stack` commands, e.g. `stack test` or `stack exec`, thus leaking host ghc package db to `ahc`, causing `ahc` to fail.
To make `ahc` work properly when called by `stack` commands, we now shadow all environment variables with name `GHC_*`/`HASKELL_*`.
> Fix test failure due to stack major upgrade

- .circleci/config.yml
Edit the circleCI config as described at https://circleci.com/blog/managing-secrets-when-you-have-pull-requests-from-outside-contributors/ so that we can enable builds on forks without having the build fail on docker and documentation builds due to secrets
> Teach circle to bail out for builds that have secrets

- ghc-toolkit/boot-libs/base/Data/Bits.hs
While this does not immediately allow a test case to pass, this + more changes should allow `arith011` to pass
> reimplement missing bits bits

- asterius/package.yaml
- asterius/test/ghc-testsuite.hs
- stack.yaml
This is possible because the new version 1.2.3 of tasty exposes
the computeStaticstics function.
Create a cross-fork pull request  for #183 to check that the new infrastructure of cross-fork circleCI will work.
Patch contributed by @timjb
> [TEST FORK CIRCLECI] Cleanup: Delete some code copied from tasty

- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/CodeGen.hs
- asterius/src/Asterius/FrontendPlugin.hs
- asterius/src/Asterius/Passes/LocalRegs.hs
- ghc-toolkit/boot-libs/rts/PrimOps.cmm
Following #187:
* `createThread` function takes zero arguments and get config from `BuiltinsOptions`.
* `ffi_mod` is fetched before we run the cmm -> wasm codegen, so in case the codegen requires `FFIMarshalState` later we can fetch it.
* We reserve another `i32` local reg for cmm functions for the "entry hook" block.
> Staging a part of ongoing async FFI work

- asterius/rts/rts.exports.mjs
- asterius/rts/rts.mjs
- asterius/rts/rts.tso.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/JSFFI.hs
- asterius/src/Asterius/JSRun/Main.hs
- asterius/src/Asterius/Ld.hs
- asterius/src/Asterius/Main.hs
- asterius/src/Asterius/Resolve.hs
- asterius/test/cloudflare/cloudflare.mjs
- asterius/test/jsffi/jsffi.mjs
- asterius/test/nomain.hs
- asterius/test/rtsapi/rtsapi.mjs
- docs/rts-api.md
Following #187 #189. This PR asyncifies the rts api everywhere (except `foreign export javascript` functions, which takes more work currently)
> Asyncify the rts api

- asterius/src/Asterius/CodeGen.hs
- asterius/src/Asterius/Passes/Relooper.hs
This PR fixes a silly bug in the relooper. Previously, when the codegen outputs a CFG, we substitute all label names with string representations of decimal numbers, and based on the assumption that the `__asterius_unreachable` label maps to the largest number, we set the fallback label to be "string of the largest number" in the relooper.
Normally, this won't be a problem, but when we're attempting to rewrite the CFG post label substitution (e.g. for async FFI), the assumption is broken, since new blocks are added and the "string of the largest number" label is non-existent. And..the substitution is not needed in the first place! We can just use the original label names per se, and simply use `__asterius_unreachable` as the fallback label.
> Fix a bug in the relooper

- asterius/rts/rts.gc.mjs
- Do what `scav.c` does: https://github.com/ghc/ghc/blob/2ff77b9894eecf51fa619ed2266ca196e296cd1e/rts/sm/Scav.c#L1950
This also led to the discovery of the same bug _upstream_ from
`Printer.c`:
https://github.com/ghc/ghc/blob/2ff77b9894eecf51fa619ed2266ca196e296cd1e/rts/Printer.c#L615
The MR fixing `ghc` upstream is at:
https://gitlab.haskell.org/ghc/ghc/merge_requests/1324
> Fix dynamic pointer tagging issue in GC.

- utils/v8-node.py
Some google internal frontend change broke our script for fetching V8 team's node build. This PR unbreaks the script.
> Fix v8-node.py

- asterius/rts/rts.messages.mjs
This PR fixes the broken browser target. When implementing `debugBelch2` for `Debug.Trace`, we added a node-only `import` which couldn't be resolved in browsers. Since the format string is always `%s\n` in practice, so we ignore the passed in `fmt` parameter for now.
To prevent similar regressions in the future, we really need to set up headless chrome/firefox unit tests.
> Fix broken browser target

- asterius/rts/rts.gc.mjs
This PR fixes handling of `IND` heap objects in gc:
* When evacuating an `IND` object, we no longer copy it; instead we evacuate its `indirectee` and return the new address, thus removing the indirection. This was supposed to be an important optimization of ghc rts.
* The scavenging code of `IND` didn't properly set the `indirectee` field to the new address..now that `IND` is eliminated in `evacuateClosure`, we might not go through this branch any more, but still we fixed it.
> Fix handling of IND objects in gc

- asterius/rts/rts.mjs
This PR fixes the `makeHaskellCallback*` functions in `rts.mjs`, switching to use `rts_mkStablePtr` instead of `rts_mkInt` to construct `JSVal` closures on the heap. We switched the internal representation of `JSVal` to `StablePtr` a long time ago but missed the update here.
> Fix makeHaskellCallback* implementation

- asterius/rts/rts.exports.mjs
- asterius/rts/rts.mjs
- asterius/src/Asterius/JSFFI.hs
This PR optimizes the experience of passing `JSVal` as parameters and return value of exported functions.
Previously, users needed to manually create `JSVal` ids for parameters, and unwrap the result `JSVal` id to fetch the real JavaScript value. Now users can pass arbitrary JavaScript values directly as parameters, and get the JavaScript result value.
For example, say that we exported `f :: JSVal -> IO JSVal` in `x.hs`. In the entry module, we can just use `await i.exports.f(any_js_value)` to call `f` and get the result.
> Optimize JSVal marshaling for exported functions

- .circleci/config.yml
- asterius/src/Asterius/Internals/Temp.hs
- asterius/test/ghc-testsuite.hs
This PR improves our current CircleCI workflow: the building & booting process is now only run once, then the build data is persisted through a workspace, shared by all downstream testing jobs. This reduces the demand for concurrent CircleCI build slots and cuts down the project's carbon footprint for the sake of this planet.
> Improve CircleCI workflow

- asterius/rts/rts.integer.mjs
- asterius/test/fib/fib.hs
Fixes #208 
Maybe we should add a test to `numeric` or some such _upstream_, since this does not seem to have coverage.
> Fix read double: integerLog2IsPowerOf2# returns 0 if it IS a power of 2

- asterius/boot.sh
- asterius/rts/rts.fs.mjs
- asterius/rts/rts.messages.mjs
- asterius/rts/rts.mjs
- asterius/src/Asterius/Builtins.hs
- ghc-toolkit/boot-libs/base/Asterius/TopHandler.hs
- ghc-toolkit/boot-libs/base/GHC/IO/Handle.hs
- ghc-toolkit/boot-libs/base/GHC/IO/Handle/FD.hs
- ghc-toolkit/boot-libs/base/GHC/IO/Handle/Internals.hs
- ghc-toolkit/boot-libs/base/GHC/IO/Handle/Text.hs
- ghc-toolkit/boot-libs/base/GHC/IO/Handle/Types.hs
- ghc-toolkit/boot-libs/bytestring/Data/ByteString.hs
- ghc-toolkit/boot-libs/bytestring/Data/ByteString/Builder/Internal.hs
- ghc-toolkit/boot-libs/bytestring/Data/ByteString/Internal.hs
- ghc-toolkit/boot-libs/unix/System/Posix/IO/Common.hsc
As a part of the migration from using an ad hoc ghc-head revision to ghc-8.6.5, we're identifying and getting rid of legacy hacks in our boot libs. This PR removes all `Handle` related hacks in `base`/`unix`.
Now the original `Handle` type works out of the box at least for `stdout`/`stderr`, which is sufficient to support the tests. They are flushed by the top handler when `main` exits.
> Get rid of `Handle` related hacks in `base`/`unix`

- ghc-toolkit/boot-libs/base/GHC/Fingerprint.hs
- ghc-toolkit/boot-libs/base/configure.ac
This PR removes a hack related to md5 in `configure.ac` of `base`. Previously the `AC_CHECK_TYPE` for `struct MD5Context` always failed since the include paths only work in a ghc build tree instead of asterius boot; we had to allow the failure and manually set the size via a CPP macro. Now we correct the include paths; as usual, the less hacks the better.
> Remove md5 hack in configure.ac of base

- asterius/rts/rts.integer.mjs
- asterius/rts/rts.mjs
- ghc-toolkit/boot-libs/base/GHC/Show.hs
This PR removes our custom `integerToString` implementation and re-enables the Haskell implementation in `base`. We disabled the Haskell implementation when we first landed the `BigInt`-based Integer library, but due to some heisenbug it outputs a wrong `String`, so we had to build the `String` on the heap on the JavaScript side. Now we can remove this hack.
> Remove hack of integerToString

- asterius/package.yaml
- asterius/src/Asterius/Foreign.hs
- asterius/src/Asterius/Foreign/Internals.hs
- asterius/src/Asterius/FrontendPlugin.hs
- asterius/src/Asterius/JSFFI.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/FrontendPlugin.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Hooks.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Orphans/Show.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Run.hs
This PR is intermediate work of gen2 JSFFI: instead of working with parsed AST, we do the work during typechecking/desugaring, hopefully solving the following problems of gen1 JSFFI:
* Not supporting type synonyms & `newtype`s of argument & return types in foreign declarations
* Needing a link-time rewriting pass to handle async imports, which is slow and fragile, and chokes non-main linking as spotted in our ongoing effort to implement TH
The approach now is much closer to what ghcjs does. This PR migrates only import-related logic and doesn't affect the link-time rewriting yet. If it works well subsequent PRs will remove all gen1 logic.
> Gen2 JSFFI part I

- asterius/src/Asterius/Foreign.hs
- asterius/src/Asterius/Foreign/Internals.hs
- asterius/src/Asterius/FrontendPlugin.hs
- asterius/src/Asterius/JSFFI.hs
Following #245, this PR migrates `foreign export javascript` handling to typechecker/desugarer.
> Gen2 JSFFI part II

- asterius/src/Asterius/CodeGen.hs
- asterius/src/Asterius/Foreign/Internals.hs
- asterius/src/Asterius/Passes/SafeCCall.hs
- asterius/src/Asterius/Resolve.hs
Following #245 #246, this PR moves the link-time rewriting pass `SafeCCall` to compile-time. When processing a call to an async import, it no longer requires the `FFIMarshalState` containing the import's information, thus working around the non-main linking problem related to async imports.
Ideally, there should be no "rewriting" on the wasm level at all. When doing STG -> Cmm we should be smart enough to emit extra basic blocks and handle suspending/resuming logic, but I've run out of recent passion quota for diving deeper into ghc. Let's spare this kind of nice-to-haves to months later.
> Gen2 JSFFI part III

- asterius/src/Asterius/Boot.hs
- asterius/src/Asterius/Foreign.hs
- asterius/src/Asterius/FrontendPlugin.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Compiler.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/FrontendPlugin.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Hooks.hs
This PR cleans up some unused code:
* In `Asterius.Foreign`, we now rely on exported functions of `DsForeign`/`TcForeign` as long as they're not modified.
* In `ghc-toolkit`, we only preserve the logic about STG and raw Cmm; all else is not necessary.
> Cleanup some unused code

- .circleci/config.yml
- Dockerfile
- asterius/app/ahc-ld.hs
- asterius/src/Asterius/JSRun/NonMain.hs
- asterius/src/Asterius/Ld.hs
- asterius/src/Asterius/Resolve.hs
- asterius/test/nomain.hs
- stack.yaml
* Fix broken `--bundle` flag in the Docker image
* From ongoing TH work: add `linkModule` for supplying in-memory `AsteriusModule`, which come from compiled splices
* Bump deps again, update ghc bindists which contain more...hooks. Sigh.
* Mark linux64 ghc bindists as `tinfo6` properly to avoid duplication with vanilla `tinfo6` bindists.
It's a pity that the attempt to fix `JSRun` using the new hooks turned out to be another rabbit hole. As demonstrated in https://gist.github.com/TerrorJack/fe89fb497f215aa433783adbf8d79357, we can intercept the iserv commands related to linking now, so given a Haskell module, we can trace the linking commands to find its deps and properly assemble the in-memory linker input, instead of having to do a regular `ahc-link` run and deserialize the linker …
> Misc fixes & improvements

- utils/clean.sh
- utils/coffee-break.sh
- utils/noon-break.sh
- utils/readme.md
This PR adds two util scripts for convenient cleaning and rebuilding:
* `utils/coffee-break.sh` cleans up `ghc-toolkit`/`asterius`, rebuilds them, and executes `ahc-boot` with all CPU cores.
* `utils/noon-break.sh` does something similar, but disables parallelism for `ahc-boot` for deterministic ABI of boot cache, and flips on `ASTERIUS_DEBUG` so that IR dumps of boot libs are enabled, and Core/STG/Cmm linting is done. Takes longer time.
When rebooting is required, execute one of these scripts from the project root directory for proper cleaning and rebooting. Rebooting should be done when:
* The toolchain (underlying `ghc`) is updated
* Boot libs in `ghc-toolkit` is modified
* Wasm codegen logic in `asterius` which affects Cmm2Wasm is modified
> Util scripts for cleaning & rebuilding

- asterius/rts/rts.exception.mjs
- asterius/rts/rts.gc.mjs
- asterius/rts/rts.mjs
- asterius/rts/rts.threadpaused.mjs
- asterius/src/Asterius/Internals/ByteString.hs
- asterius/src/Asterius/JSGen/Constants.hs
- asterius/src/Asterius/Main.hs
This PR changes rts js code and the js codegen in the following ways:
* We used to have an "info table check" in rts js code; it requires the set of all info pointer addresses to be emitted into the `.lib.mjs` script which bloats the script size. Now it's only enabled in the debug mode. (#299)
* We used to have a set of "pinned static closures" which are also gc roots, and they require special handling in gc. Now they're renamed to "export stable pointers" and are handled as vanilla stable pointers. (#301)
* The event logger no longer defaults to emitting every single event via `console.log`. Until we figure out a proper event log story, it's fine the way it is.
> Various changes in the js codegen

- asterius/rts/rts.scheduler.mjs
Display the stack trace on error. Compare:
Before:
```
RuntimeError: TypeError: Cannot mix BigInt and other types, use explicit conversions
at file:///home/hsyl20/repo/asterius/diagrams/asterius/test/diagrams/rts.scheduler.mjs:264:17
ahc-link: callProcess: node "--experimental-modules" "SquareLimit.mjs" (exit 1): failed
diagrams: callProcess: ahc-link "--input-hs" "test/diagrams/SquareLimit.hs" "--run" "--verbose-err" "--binaryen" (exit 1): failed
```
After:
```
RuntimeError: TypeError: Cannot mix BigInt and other types, use explicit conversions
at IntegerManager.timesInteger (file:///home/hsyl20/repo/asterius/diagrams/asterius/test/diagrams/rts.integer.mjs:83:40)
at __asterius_jsffi_integerzmwiredzminzuGHCziIntegerziType_a1Ev (file:///home/hsyl20/repo/asterius/diagrams/asterius/test/diagr …
```
> Display stack trace on error

- .circleci/config.yml
This PR is a series of PRs to split up #321 
Previously, we did #244 to throttle our CircleCI jobs by rearranging them, so that the more time-consuming `asterius-ghc-testsuite` jobs are run only after `asterius-test` passes, and more expensive flavours of `asterius-ghc-testsuite` are run after cheaper flavours. Now this becomes troublesome since when working on major changes, we may break regular tests, but we'd still like `asterius-ghc-testsuite` to run early so we get some intuition on how bad the breakage is.
> Remove CircleCI rate limit

- .circleci/config.yml
- asterius/src/Asterius/GHCi/Internals.hs
- asterius/src/Asterius/JSRun/Main.hs
- asterius/src/Asterius/JSRun/NonMain.hs
- asterius/src/Asterius/Main.hs
- asterius/test/ghc-testsuite.hs
- asterius/test/jsffi/jsffi.mjs
- asterius/test/rtsapi/rtsapi.mjs
Previously, the linker generates a `xxx.lib.mjs` script, which exports a function, taking the compiled `WebAssembly.Module` value as input, generating an asterius instance as output. The function is then used in the entry script `xxx.mjs`. However, the function just applies the `newAsteriusInstance` function exported by `rts.mjs` to the "request object" generated by the linker, and it would be better to simply just export the "request object" itself directly. Thus:
* The entry script and the various "runners" (which use `inline-js-core` to control evaluation) only needs to apply `newAsteriusInstance` manually, not much additional work
* The request object can be **modified**. For instance, later we'll need to assign a new field `persistentState` to it, passing state from the *previous* …
> Export "request object" directly in link-time generated JavaScript

- asterius/src/Asterius/Passes/GCSections.hs
- asterius/src/Asterius/Resolve.hs
Previously we piled quite a lot of linker logic into `Asterius.Resolve`; this PR moves out the dead code elimination logic out of `Asterius.Resolve` to a separate optional pass. This is a part of efforts to clean up the linker mess and prepare a cleaner foundation for incremental linker work.
> Move DCE logic to a proper pass

- .circleci/config.yml
- Dockerfile
- asterius/app/ahc-cabal.hs
- asterius/app/ahc-ld.hs
- asterius/src/Asterius/FrontendPlugin.hs
Whatever not tested on CI should be assumed broken. And at least not the case anymore for `ahc-cabal`..
Changes:
* Previously, `ahc-cabal` works by intercepting command-line arguments, adding a bunch of asterius-specific stuff and passing to `cabal`; it requires quite a bit of knowledge about how `cabal` arguments are parsed, and only work for a certain set of "common" commands. Now we take an alternative approach: obtain the cabal config file path, create and supply a temporary config file which is patched with `cabal user-config update`. This is simpler and works for all cabal commands.
* The frontend plugin of `ahc` now always hard-code the `ahc-ld` as the linker, so no need for passing `-pgml` from the command line
* The `ahc-ld` executable used to expect a `--prog-name` switch which …
> Fix & test ahc-cabal

- asterius/rts/rts.stableptr.mjs
Related: #320 
We temporarily disable `JSVal` GC to mitigate the `Integer` use-after-free issue for the time being. @hsyl20's new generation `Integer` library will soon save us from this mess, so imho we better not spend a lot more time to rewrite `integer-simple` to fix it :)
> Mitigate Integer use-after-free issue

- asterius/src/Asterius/Foreign.hs
- asterius/src/Asterius/Foreign/Internals.hs
This PR contains misc fixes to FFI stuff:
* For the value types of JSFFI imports, we now support the `IntX`/`WordX` types in `Data.Int`/`Data.Word`.
* In our hooked `asteriusTcCheckFIType`/`asteriusDsCImport` functions, we now provide more informative error messages upon cases we can't handle yet.
> Misc FFI-related fixes

- asterius/rts/rts.text.mjs
- asterius/src/Asterius/Builtins.hs
Related: #357 #347 
This PR uses W3C `TextDecoder` and `TextEncoder` to implement UTF-8 codec functions: `_hs_text_decode_utf8` and `_hs_text_encode_utf8`, which are required by `Data.Text.Encoding` and `aeson` related code.
The behavior of `_hs_text_decode_utf8` diverges with original c version with illegal input; in which case a runtime error is thrown in js and can't be handled in hs. It's possible to implement correct "stop at first illegal code point" behavior by bisecting the source buffer and feeding to `TextDecoder`, but IMHO that's more work and should be fixed in future PRs.
> Implement missing utf8 codec cbits for text

- asterius/rts/rts.fnv.mjs
- asterius/rts/rts.md5.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Builtins/Hashable.hs
- asterius/src/Asterius/EDSL.hs
Related: #358 #146 
We already have 128-bit FNV-1a algorithm implemented in `rts.md5.mjs` as pseudo-MD5 to be used by `GHC.Fingerprint` logic. This PR factors out the hashing logic, and implements interface for both `GHC.Fingerprint` logic and `hashable` logic. `hashable` uses 64-bit hashing, so the resulting 128-bit result shall be truncated before returning.
Side note: maybe we should also use `arithmoi` to write a script for a principled way of generating magic numbers for FNV hashing.
> Migrate 128-bit FNV-1a logic to be used by base and hashable

- asterius/rts/rts.fnv.mjs
- asterius/rts/rts.md5.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Builtins/Hashable.hs
- asterius/src/Asterius/EDSL.hs
- ghc-toolkit/boot-libs/asterius-prelude/asterius-prelude.cabal
- ghc-toolkit/boot-libs/asterius-prelude/src/Asterius/Aeson.hs
- ghc-toolkit/boot-libs/asterius-prelude/src/Asterius/UTF8.hs
Addresses #347. To be reviewed after #361 is merged and this one is rebased.
This PR implements `Asterius.Aeson` providing:
```haskell
jsonToJSVal :: ToJSON a => a -> JSVal
jsonFromJSVal :: FromJSON a => JSVal -> Either String a
```
This enables marshaling between Haskell datatypes with `FromJSON` & `ToJSON` instances with JavaScript values. It calls `JSON.stringify` & `JSON.parse` under the hood, and so we also need to implement marshaling between UTF-8 encoded lazy `ByteString`s and UTF-16 encoded `JSString`s. 
This is enough to get stuff working for now, but `aeson` marshaling logic looks like a hot spot in typical applications so in the future we may still need some dark arts to speed things up.
> Implement `aeson` conversion interface

- asterius/app/ahc-cabal.hs
- asterius/app/ahc-pkg.hs
This PR is a result of much frustration brought by "package environment files" which polluted @hsyl20's local environment and prevented `ahc-boot` to properly run. Following instruction in https://gitlab.haskell.org/ghc/ghc/issues/13753, we instruct `ahc-cabal` to set `package-env: -` to disable them. Also, `ahc-pkg` now implements the same hack of `ahc-cabal` and `ahc` to prevent pollution of `GHC*` & `HASKELL*` related env vars, so it should work fine when directly invoked with `stack exec`.
> Turn off package environment files in `ahc-cabal`

- asterius/test/nomain.hs
- lts.sh
Changeset:
* We used to have `--no-gc-sections` for the `nomain` test, so to stress test the linker & runtime by collecting everything into the resulting wasm. Since #348 the global pkgdb has grown quite a bit so `--no-gc-sections` would generate wasm files which are too large to be loaded. Maybe we should remove this flag but that belongs to a future PR.
* We chop off some more packages in the docker image build script to further reduce timeout possibility.
> Fix CI on the `master` branch

- asterius/boot.sh
- ghc-toolkit/boot-libs/text/Data/Text/Lazy/Encoding.hs
`decodeUtf8With` for lazy `Text` uses a streaming UTF-8 parser in cbits which is too troublesome to port right now. So we implement a not so efficient workaround here: we patch `text` and call the already working `decodeUtf8` function for strict `Text`, then convert it back. This shall close #357 and unblock #315.
In the longer run, since patching `text` is unavoidable, we shall simply get rid of `ccall` interfaces for `text` parsers, and introduce stateful parsing with `TextDecoder`; combined with bisection on input buffer, it should also be possible to stop at first illegal codepoint and enable proper error handling on the haskell side.
> Quick fix of `decodeUtf8With` for lazy `Text`

- asterius/rts/rts.constants.mjs
- asterius/rts/rts.gc.mjs
- asterius/rts/rts.memory.mjs
- asterius/rts/rts.memorytrap.mjs
- asterius/src/Asterius/JSGen/Constants.hs
Diagrams example showed that pointer manipulation in JS rts takes a lot of time. This MR makes `unTag`, `getDynTag` and `bdescr` faster.
> Enhance runtime performance

- asterius/rts/rts.gc.mjs
- asterius/rts/rts.memory.mjs
Reduce GC duration from ~150ms to ~65ms in SquareLimit example (cf #374)
> Enhance performance by avoiding BigInt when possible

- .circleci/config.yml
- Dockerfile
- npm-utils/Setup.hs
- stack.yaml
Notable changes:
* The bindists are no longer configured with `--enable-dwarf-unwind`, since we don't use them for the host libraries. The runtime environment doesn't require `libdw` anymore.
* The macos bindist is built with xcode 11.2.1 and macos catalina. `coreutils` from `brew` is removed from `$PATH` when building, maybe this will help with fixing darwin support.
* `inline-js` is bumped to contain upstream improvements.
* The stackage snapshot version is bumped to `lts-14.16`.
* We now fix the `parcel-bundler` version when installing `npm-utils`.
We're leaving out `binaryen` and `wabt` in this bump. They'll be updated when appropriate.
> Bump various deps

- .circleci/config.yml
- Dockerfile
- asterius/app/ahc-cabal.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/FakeGHC.hs
This PR doubles the dose of hack introduced in #344. When we attempt to compile the custom `Setup.hs` script with the host ghc, it may fail (e.g. lacking certain `custom-deps`), in which case we resort to compiling & using a `Setup.hs` that implements `build-type: Simple` behavior.
This hack is even grosser, but it fixes the building of the kmettverse packages (up to `lens` at least). Because kmettverse packages has a constant pattern of using `Setup.hs` with `cabal-doctest` for doctests, and since we aren't running tests anyway, the packages build fine with the default `build-type: Simple` script.
> Hack to support kmettverse packages

- asterius/app/fs.c
- asterius/app/fs.h
- asterius/app/unlit.c
- asterius/package.yaml
- asterius/src/Asterius/BuildInfo.hs
- asterius/src/Asterius/FrontendPlugin.hs
When trying to build `cubicbezier` (which is a transitive dependency of `diagrams`), `ahc` complains about the lack of the `unlit` executable. I have no idea why `unlit` is required since:
* `Cabal` implements the unlit logic as pure Haskell and should use that when preprocessing literate sources
* `unlit` isn't present in the bindir of a vanilla `ghc` installation
But anyway. This PR adds the `unlit` source code copied from `utils` of `ghc` and hard-wire the installed `unlit` path as the unlit program. Combined with #381, we are able to build `diagrams` along with all its dependencies.
> Add the unlit executable

- .circleci/config.yml
- asterius/rts/rts.gc.mjs
- asterius/rts/rts.heapalloc.mjs
- asterius/rts/rts.mjs
- asterius/src/Asterius/JSRun/NonMain.hs
- asterius/src/Asterius/Main.hs
A rework of #378.
We now have a `--gc-threshold` option for `ahc-link` & `ahc-dist`. When a heap overflow occurs and `performGC` is entered, it queries the current state of `HeapAlloc` and calculates the total live mblock number. If it's below the "gc threshold" value (which defaults to 64), then it skips GC logic like the yolo mode. This should avoid a lot of GC invocations as shown in the flame graph in #374, working around our lack of generational collection.
> To collect sometimes, to allocate always

- asterius/src/Asterius/GHCi/Internals.hs
Closes #384. This also requires a hack in upstream `inline-js`, see https://github.com/tweag/inline-js/pull/53 for details.
> Do not hang ahc when TH runner crashes

- asterius/src/Asterius/Main.hs
Closes #364.
We used to emit `import foo from "./foo.req.mjs"` in `foo.mjs` for `foo.hs` main modules, but when the module name contains slashes, `foo-bar` isn't a valid js identifier and this results in runtime syntax errors.
> Fix the request object name in default entry script to `req`

- utils/readme.md
- utils/stack-ide.sh
`utils/stack-ide.sh` can be useful as a last-resort "IDE" when working on the Haskell sources of `asterius`. It's a pity we don't have proper `ghcid` support for now (see #395), but having this script is better than having a typechecker in my brain.
> Add stack-ide.sh

- asterius/src/Asterius/Backends/Binaryen.hs
- asterius/src/Asterius/Backends/WasmToolkit.hs
- asterius/src/Asterius/Types.hs
This PR recovers the support for the `TeeLocal` opcode. It's not used by our cmm-to-wasm codegen, but used by `clang`, and one of `cmath` functions depends on it.
> Recover support for the TeeLocal opcode

- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Builtins/CMath.hs
This PR adds implementation of the `scalbn` function in libc, which is used by `__word_encodeDouble` in `integer-simple`.
The code in `CMath.hs` doesn't need to be reviewed; it is expression IR without using EDSL, hand-written by peeking the disassembled output of `wasi-sdk` compiled `musl`. We really need more principled automatic disassembling to make use of more libc functions in the long run though; I definitely don't want to do this twice
> Add cmath cbits

- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Builtins/StgPrimFloat.hs
This PR implements parts of `StgPrimFloat.c` in ghc rts: `__word_encodeDouble` and `__word_encodeFloat`, which is used by stock `integer-simple`.
> Implement parts of StgPrimFloat

- asterius/rts/rts.float.mjs
- asterius/src/Asterius/Builtins.hs
This PR implements `__decodeDouble_2Int`, which is just wrapping existing implementation in `rts.float.mjs`. In the future this kind of bit-fiddling code should be rewritten in pure wasm.
> Implement __decodeDouble_2Int

- asterius/src/Asterius/Backends/Binaryen.hs
- asterius/src/Asterius/JSRun/NonMain.hs
- asterius/src/Asterius/Main.hs
This PR runs the `limit-segments` pass of `binaryen` after performing optimization. This is necessary for large outputs with lots of segments, since output wasm modules with more than 100000 segments has been spotted more than once in the wild.
We also disable binaryen optimization and shrinking for the TH runner, since the splice code is short-lived anyway so we shouldn't waste more CPU cycles there.
> Run limit-segments pass after binaryen optimization

- .circleci/config.yml
- asterius/test/.gitignore
- asterius/test/cloudflare.hs
- asterius/test/cloudflare/cloudflare.hs
- asterius/test/cloudflare/cloudflare.mjs
- asterius/test/cloudflare/package.json
- asterius/test/cloudflare/test.js
This PR attempts to address most of #290.
There is a bit more JS code in `cloudflare.mjs` to hande the initialization of Asterius's runtime and the `fetch` event listener.
`cloudflare.hs` exports a handler function instead of having a `main` function. (Note: the handler looks identical to [this template project's](https://github.com/ento/worker-haskell-template/blob/3b393e2027013fbbe2b749047508a912de5c1108/src/worker.hs) because both this PR and that template project grew organically out of my attempt to use Asterius to write a Cloudflare Workers script.)
There is also a fair bit of JS code in `test.js` to test the compiled code using "@dollarshaveclub/cloudworker". This _could_ be written in Haskell, which would launch `cloudworker` as a child process and send test requests against it. …
> Fix the Cloudflare Worker example and enable its test in CI

- asterius/package.yaml
- asterius/rts/browser/default.mjs
- asterius/rts/node/default.mjs
- asterius/rts/rts.constants.mjs
- asterius/rts/rts.mjs
- asterius/rts/rts.time.mjs
- asterius/src/Asterius/JSGen/Constants.hs
- asterius/src/Asterius/Main.hs
- asterius/src/Asterius/Main/Task.hs
- asterius/test/time.hs
- asterius/test/time/time.hs
- ghc-toolkit/cbits/ghc_constants.c
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Constants.hs
This is work in progress to enable the asterius runtime to import a different module according to the deployment target (for now, either Node.js or the browser).
This target-specific module should provide a target-independent interface for methods useful to other classes: for instance, the Performance API that we plan to use for recording statistics about garbage collection, which is currently available in browsers and node.js in a different way.
The current commit adds two new folders to the rts, `browser` and `node`, each containing a target-specific `default.mjs` file (currently a stub, to be filled later). The `target` attribute in a `Task` object determines which folder to copy at link time. 
The target-specific import is obtained by a dynamic import performed inside the JS `req` …
> Implementing Performance API

- asterius/rts/rts.gc.mjs
- asterius/rts/rts.heapalloc.mjs
- asterius/rts/rts.memory.mjs
This PR adds more comments to the source code of the asterius RTS, in particular to the source files related to memory management and garbage collection (i.e. `rts.memory.mjs`, `rts.heapalloc.mjs`, `rts.gc.mjs`).
The goal is to clarify the current logic of GC, in order to make more straightforward hacking garbage collection in the future so to improve performance.
The added comments are in JSDoc format, so that documentation can later be easily generated.
> (WIP) More comments in the RTS source code

- asterius/rts/rts.gc.mjs
During copying garbage collection, the GHC runtime employs so-called "forwarding pointers", i.e. it replaces the header word of the object that is being copied with a pointer to the new copy. In addition to overwriting the header, the least-significant bit must be set to 1, in order to be able to distinguish a forwarding pointer from a pointer to the info table.
The `asterius` RTS currently does not exploit forwarding pointers, and instead uses `GC.closureIndirects` to map the address of an evacuated object to its copy.
This PR adds support for forwarding pointers to `asterius`.
> Use forwarding pointers during GC

- .envrc
This PR adds a `.envrc` file to the project root. When `direnv` is set up in the dev environment, this exposes executables like `ahc` to `PATH`, so testing small examples locally would only need `ahc-link ...` without typing `stack exec`.
One downside of the `.envrc` file is slightly slowing down a `bash` session startup since it invokes `stack path` multiple times; the lag is more significant when the project tree is fresh and there isn't a local setup of the custom ghc bindists, since `stack path` may also enter the logic of bindist setup. However, `divenv` always allow a Ctrl+C escape from a long running `.envrc` script, so it shouldn't be a big concern.
> Add a direnv config file for convenience

- .circleci/config.yml
When curating the new docker images for `lts-14.21`, we discovered regressions in the TH runner for `contravariant-extras-0.3.5` and `cql-4.0.2`, which prints gc-related rts error message:
```
RuntimeError: RuntimeError: Invalid live mblock 0x1ffff700100100
at HeapAlloc.handleLiveness (file:///home/asterius/.asterius/.stack-work/install/x86_64-linux-custom-asterius-tinfo6/a6f37316a3da926688ff81f5b3da56a72cf3b7b83dd723525b6931d11f77da34/8.6.5/share/x86_64-linux-ghc-8.6.5/asterius-0.0.1/rts/rts.heapalloc.mjs:172:15)
at GC.performGC (file:///home/asterius/.asterius/.stack-work/install/x86_64-linux-custom-asterius-tinfo6/a6f37316a3da926688ff81f5b3da56a72cf3b7b83dd723525b6931d11f77da34/8.6.5/share/x86_64-linux-ghc-8.6.5/asterius-0.0.1/rts/rts.gc.mjs:863:20)
at Scheduler.returnedFromTSO …
```
> Test more cabal packages on CI

- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Builtins/CMath.hs
- asterius/src/Asterius/Builtins/StgPrimFloat.hs
- asterius/src/Asterius/CodeGen.hs
- asterius/src/Asterius/EDSL.hs
- asterius/src/Asterius/EDSL/BinaryOp.hs
- asterius/src/Asterius/EDSL/UnaryOp.hs
- asterius/src/Asterius/Passes/GlobalRegs.hs
- asterius/src/Asterius/Passes/MergeSymbolOffset.hs
- asterius/src/Asterius/Passes/SafeCCall.hs
This PR adds a simple improvement to the EDSL: all unary/binary ops are added as `Expression -> Expression` and `Expression -> Expression -> Expression` functions. When building `Expression`s in the `asterius` codebase, we can avoid writing `Unary` and `Binary` records.
The EDSL improvements are scheduled before migrating more rts js logic to wasm.
> Make sure all unary/binary ops are present in the EDSL

- .circleci/config.yml
- asterius/package.yaml
This PR tunes the rtsopts in the CI script and `asterius` executables:
* We used to use `GHCRTS` environment variable to pass `-N` to the `asterius` executables. This optimization does more harm than good:
* We had to patch `ghc-pkg` and `hsc2hs` since their executables aren't linked with `-threaded -rtsopts`
* `ahc-cabal` already has package-level parallelism when booting
* `GHCRTS` is removed in the jobs other than `ghc-testsuite`. This also slightly reduce our work to maintain the forked ghc, since we don't need to work with an `hsc2hs` fork anymore
* The `asterius` executables are still linked with the threaded rts, and additionally with larger default nursery size, with parallel gc and idle gc disabled.
The combined effect is slightly improved CI and docker image build time. And it …
> Tune rtsopts for asterius executables

- ghc-toolkit/Setup.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/GenPaths.hs
On top of #437 
This PR fixes `ghc-toolkit` to support being compiled by `Cabal-3`, since there are breaking changes in `Cabal` public API as usual. Note that this doesn't mean `ghc-toolkit` automatically works with `ghc-8.8`; the `8.8`-specific fixes of the library and the shipped boot lib artifacts are present in other branches.
> Fix Cabal 3 support of ghc-toolkit

- asterius/rts/rts.gc.mjs
- asterius/src/Asterius/Ld.hs
_Selector optimisation_ is a known optimisation where thunks of applications of field selectors are evaluated during garbage collection, so to avoid space leaks caused by unused fields that look alive.
This PR fixes #422 by introducing the new function `GC.stingyEval`, which shorts-out chains made out of selector/constructor and/or indirections (also interleaved).
Note: `GC.stingyEval` uses a technique called _whiteholing_, where closures in the chain that is being explored are replaced with "whiteholes", in order to not diverge in case of cyclic closures.
> Implement selector optimisation

- asterius/rts/browser/default.mjs
- asterius/rts/node/default.mjs
- asterius/src/Asterius/Builtins/Posix.hs
Following #441, this implements `stat`, `readdir` and `closedir` for the node `rts`.
One annoyance when doing this PR: `unix` uses the `capi` convention for `opendir`. When implementing `opendir` as a builtin function, we have to query the complete unit-id of `unix` in order to assemble the complete `opendir` symbol name. In order to do that, we launch a GHC API session and query the global package database. This is not neat. Patching `unix` can spare us this trouble but I'd like to avoid patching standard libs for now..
Another annoyance: `readdir` needs to pass `dirent` entries on every invocation. The POSIX standard says: don't call `free()` on the returned pointer, since it might be in a static section! Which means it's global. And not thread-safe. So here we have the same pitfall: we …
> Implement POSIX File I/O for rts, part II

- asterius/app/ahc-ld.hs
This PR adds an "ignore" option to `ahc-ld`: when `ASTERIUS_AHC_LD_IGNORE` is set in the environment variables, `ahc-ld` skips linking logic and simply touches the output executable path.
This is not intended to be used by end-users of `asterius`; but it's useful for the docker image builder, since we always delete the pseudo-executables of prebuilt packages anyway, and it would be better to avoid actual linking in the first place.
> Add "ignore" option to ahc-ld

- asterius/rts/browser/default.mjs
- asterius/rts/node/default.mjs
- asterius/src/Asterius/Builtins/Posix.hs
More POSIX stuff.
* We didn't have any handling of `errno` before; `get_errno` always returned `0` and `set_errno` was a no-op. When a `node` syscall throws, the rts would simply crash. Now, we catch the js exceptions and make the `errno` information available through the getter/setter functions.
* More POSIX stuff on the `node` side: `getenv`, `access`, `getcwd`.
> More POSIX stuff

- asterius/rts/rts.scheduler.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Builtins/SM.hs
This PR implements growable stacks. Previously, our stack size is hard-wired to `65536` (actually a bit less), and when the stack space runs out, the runtime simply panics. Now, we would allocate a new stack object with twice the size, copy the stack frames there, and resume execution. The default stack size is also cut down to `4096` now since small stacks should be sufficient most of the time. This is a critical runtime improvement that should have been done quite some while ago..
There are still possible improvements in this space, but they shall be done in future PRs:
* Unpin the TSO and stack objects
* Set maximum stack size threshold, and when the stack grows beyond the threshold, throw a `StackOverflow` exception in the offending Haskell thread instead of a runtime panic
* …
> Implement growable stack

- asterius/src/Asterius/Backends/Binaryen.hs
- asterius/src/Asterius/Backends/WasmToolkit.hs
- asterius/src/Asterius/CodeGen.hs
- asterius/src/Asterius/CodeGen/Droppable.hs
- asterius/src/Asterius/Types.hs
Should close #450. Repro: any demo which links in a reverse dep of `memory`.
This hack may go away in the future if we fundamentally change how `ccall`s are handled (e.g. using the convention implemented in `clang`, or rolling our own `libffi`-like calling convention).
> Enable certain ccall results to be dropped

- stack.yaml
Our `binaryen` build script uses `cmake -S .. -B ..` to specify source & build directories, but that doesn't work for `cmake` prior to `3.13`. Regression discovered by @gkaracha when building on `ubuntu:bionic`.
> Fix `binaryen` building for older `cmake` versions

- .envrc
- .gitignore
The previous `.envrc` file calls `stack path` multiple times and is pretty slow. This PR speeds up things a bit by only calling `stack` once and exports the `PATH` from there.
Another tiny change that sneaks in: we add `/test` to `.gitignore` so it's convenient to test stuff in the project directory, call `ahc` directly without watching out accidental checking in of the artifacts.
> Avoid repeated stack invocations in .envrc

- asterius/src/Asterius/Boot.hs
- asterius/src/Asterius/CodeGen.hs
- asterius/src/Asterius/FrontendPlugin.hs
- asterius/src/Asterius/GHCi/Internals.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Compiler.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Hooks.hs
Changeset:
* Remove the unused `stg` field from `HaskellIR` for now
* Do not convert the raw Cmm `Stream` to list at once; instead, consume the `Stream` directly in the codegen
* The `CodeGen` is now a `ReaderT` over `IO` and no longer pure, but the purity has little benefit here anyway
This will hopefully cut down quite some compile-time memory usage and speed things up a bit.
> Adjust ghc-toolkit IR types

- asterius/src/Asterius/Backends/WasmToolkit.hs
Moved the elaboration of unary and binary operators to Wasm instructions into separate functions (and thus outside of `makeInstructions`):
```
marshalUnaryOp  :: UnaryOp -> Wasm.Instruction
marshalBinaryOp :: BinaryOp -> Wasm.Instruction
```
> Slightly modularize Backends.WasmToolkit.makeInstructions

- asterius/rts/rts.mjs
- asterius/rts/rts.staticptr.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Builtins/SPT.hs
- asterius/src/Asterius/CodeGen.hs
- asterius/src/Asterius/Foreign/Internals.hs
- asterius/src/Asterius/Internals/Name.hs
- asterius/src/Asterius/JSGen/SPT.hs
- asterius/src/Asterius/Main.hs
- asterius/src/Asterius/Passes/GCSections.hs
- asterius/src/Asterius/Resolve.hs
- asterius/src/Asterius/Types.hs
- ghc-toolkit/boot-libs/base/GHC/StaticPtr.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Compiler.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Hooks.hs
This PR fixes static pointers.
* In the `ghc-toolkit` IR, we add `SptEntry` list so the codegen can process them
* In the `asterius` IR, we add a mapping from static closure symbols to the SPT fingerprints. The mapping is added when we process raw Cmm compiled from Haskell
* In the linker, after the regular gc-sections pass, we pick out the subset of all SPT entries where the static closures are alive, and emit a mapping as `req.sptEntries` in the req script
* The RTS maintains a mapping from 128-bit `Fingerprint`s to static closure addresses. Upon startup, each SPT entry also gets a `StablePtr` allocated, so they become GC roots
* We needed to slightly patch `GHC.StaticPtr` in order to implement `staticPtrKeys`, since the fingerprint contents needs to be passed to a buffer allocated in …
> Fix static pointers support

- asterius/app/ahc-ld.hs
- asterius/rts/rts.exports.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Builtins/Main.hs
- asterius/src/Asterius/JSFFI.hs
- asterius/src/Asterius/Ld.hs
Previously, when we link a Haskell program with `main`, we simply ensure the `runMainIO` and `main` closures are root symbols, and the `main` method of the exports object would call `rts_apply` to create a thunk for evaluation. Come to think of it, there are two drawbacks to the approach:
* Unsafe! The `main` closure is *not* a GC root iirc. What if the exported `main` method is called multiple times, with GC triggered in between, and `main` references into the dynamic heap?
* Not elegant. `main` takes special logic in linker & runtime, but it's just yet another exported `IO a` closure.
This PR removes the `main` method in the runtime. We now handle `main` as if it's yet another `foreign export javascript` thing, but since the export declaration isn't really written by the user in the …
> Minor improvements to `main` handling

- asterius/src/Asterius/Builtins/Main.hs
- asterius/src/Asterius/JSFFI.hs
- asterius/src/Asterius/Ld.hs
- ghc-toolkit/boot-libs/base/Asterius/TopHandler.hs
Following #469, we apply the top handlers to all foreign exports:
* `Asterius.TopHandler` exports `runIO`/`runNonIO`, and their closure symbols are root symbols
* The generated JS code of foreign exports will apply the top handlers before evaluation.
For end users, this means that we now have uniform behavior for the main thread as well as user-exported functions: the `stdout`/`stderr` handles are flushed, and uncaught exceptions will be written to `stderr`.
This doesn't apply to the `makeHaskellCallback*` functions yet. Those should be deprecated in future PRs.
> Apply the top handlers to all foreign exports

- asterius/src/Asterius/JSFFI.hs
- asterius/src/Asterius/Ld.hs
- asterius/src/Asterius/Main.hs
Previously, all export closures are emitted into the runtime symbol table. This is not necessary since the relevant JS code is generated at link-time and doesn't need to be human-readable. This PR removes such symbol table entries, and use the absolute addresses of export closures in the emitted JS code.
The `runIO`/`runMainIO` symbols are also removed from the symbol table since they aren't used by the hand-written parts of the runtime. We now have a collection of "private symbol"s for the runtime, which is also a root symbol set but doesn't get emitted into the symbol table.
When linking without `main`, a dummy `main` method will still be generated, but the resulting `Promise` should reject with an unfound symbol error. This should be fine since we don't call `main` in such cases.
> Do not emit export closures into the runtime symbol table

- asterius/rts/rts.exports.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/test/nomain.hs
- asterius/test/rtsapi.hs
- asterius/test/rtsapi/rtsapi.mjs
This PR removes the `rts_eval` and `createGenThread` functions from the runtime since they're no longer used after #470.
> Remove `rts_eval` and `createGenThread`

- asterius/src/Asterius/Foreign/DsForeign.hs
- asterius/src/Asterius/Foreign/TcForeign.hs
This PR changes the typechecking/desugaring logic of `foreign import prim` and reuse `ccall` logic. This changes the `foreign import prim` semantics in the following ways:
* Lifted arguments and return types are now accepted.
* The return type can now be `IO`-wrapped.
* Unboxed tuples are no longer accepted as arguments and return types.
* `Any` and `JSVal` are special cases which allow passing managed pointers or JavaScript references.
This is the first part of upcoming Async FFI improvements since we'll desugar async calls into Cmm tail calls, and `foreign import prim` fits nicely here.
> Reuse typecheck/desugar logic for `prim`/`ccall` foreign imports

- asterius/src/Asterius/Foreign/Internals.hs
- asterius/src/Asterius/Foreign/SupportedTypes.hs
- asterius/src/Asterius/JSFFI.hs
- asterius/src/Asterius/Passes/SafeCCall.hs
- asterius/src/Asterius/Types.hs
This PR changes how `FFIValueType` is modeled:
* We now have a new `FFIValueTypeRep` which models `PrimRep` in GHC API, plus `FFIJSValRep` to indicate `JSVal`.
* From `FFIValueTypeRep` alone, we can recover the import/wrapper wasm type and signedness, so we replace those with `FFIValueTypeRep` in a `FFIValueType`. Also, `FFI_JSVAL` isn't a standalone variant of `FFIValueType` anymore.
* We now always use `F64` as the import wasm value type, and no longer support `I32` as a wrapper type.
Why do we need to model `PrimRep` in our IR? When we generate code for an async import, we need to generate custom Cmm code, and it's important to distinguish managed pointers with regular bits. A more detailed explanation will follow in subsequent PRs.
> Change the representation of `FFIValueType`

- asterius/src/Asterius/FrontendPlugin.hs
This PR flips on `-feager-blackholing`. This should be a good default compared to lazy blackholing:
* Two additional store instructions when entering a thunk. No atomic instruction here so the additional overhead is quite small.
* Drop references to thunk free variables early. May help in reducing heap residency.
* Help catching cyclic data dependency and avoiding wasted calculation of thunks.
* No need for a stack traversal to update the update frames in `threadPaused`.
The proper implementation of `messageBlackhole` and `updateThunk`, as well as the logic of throwing non-termination exceptions or resurrecting threads blocked on a thunk, will follow in subsequent PRs.
> Use eager blackholing for thunk entry code

- .devcontainer/Dockerfile
- .devcontainer/build.sh
- .devcontainer/devcontainer.json
- .envrc
This PR adds the configuration for [vscode remote containers](https://code.visualstudio.com/docs/remote/containers). For vscode users, setting up the dev environment for hacking on asterius should be way simpler than before: do an initial build of the container, go grab a cup of tea, period. Some common tools are included in the build script: `ghcid`, `hlint`, `brittany`, `ormolu`, `wai-app-static` and `wabt`.
> Add vscode remote containers support

- .circleci/config.yml
- base.Dockerfile
- dev.Dockerfile
We now reuse the same dev image for building stuff on CI. This shaves off a lot of duplicate dependency-setup parts in the CI config and slightly speeds up things a bit since the stack package database is already populated with some common packages in the image.
> Use the dev image on CI

- .ghcid
- asterius/rts/rts.scheduler.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Builtins/Blackhole.hs
- asterius/src/Asterius/Builtins/Hashable.hs
- asterius/src/Asterius/EDSL.hs
- ghc-toolkit/cbits/ghc_constants.c
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Constants.hs
- utils/ghcid.sh
- utils/readme.md
This PR implements `messageBlackHole` and `updateThunk` rts functions, and fixes the blackholing behavior when multiple threads force the same thunk. Consider this example:
```haskell
import Control.Concurrent
import Data.Foldable
import System.IO.Unsafe
main :: IO ()
main = do
for_ [0 .. 7] $ \_ -> forkIO $ p g
p g
foreign import javascript safe "new Promise(resolve => setTimeout(() => { console.error('Resolving'); resolve(233); }, 1000))" f :: IO Int
foreign import javascript "console.error('Printing ' + ${1})" p :: Int -> IO ()
{-# NOINLINE g #-}
g :: Int
g = unsafeDupablePerformIO f
```
When eager blackholing is on (which we made mandatory previously):
* `g` should be evaluated exactly once, on the main thread
* The main thread must block once for `OnCCall`
* Other threads must block …
> Fix blackholing behavior with multi-threading

- asterius/rts/rts.exception.mjs
- asterius/rts/rts.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Builtins/Blackhole.hs
A follow-up PR of #493.
Consider this example:
```haskell
import Asterius.Types
import Control.Concurrent
import Control.Exception
import Data.Foldable
import System.IO.Unsafe
main :: IO ()
main = do
for_ [0 .. 7] $ \_ -> forkIO $ p' g
p' g
foreign import javascript safe "new Promise((resolve,reject) => setTimeout(() => { console.error('Rejecting!'); const err = new Error('BOOM'); reject(err); }, 1000))" f :: IO Int
foreign import javascript "console.error('Printing ' + ${1})" p :: JSString -> IO ()
{-# NOINLINE g #-}
g :: Int
g = unsafeDupablePerformIO f
p' :: Show a => a -> IO ()
p' x =
catch
(p (toJSString (show x)))
(\e -> p (toJSString (show (e :: JSException))))
```
The correct semantics should be: 9 different `BOOM` error messages with their JS stack traces written to the console. …
> Use generic updateThunk() when handling update frames upon exceptions

- asterius/package.yaml
- asterius/src/Asterius/Foreign/Internals.hs
- asterius/src/Asterius/JSFFI.hs
- asterius/src/Asterius/Types.hs
- asterius/test/array/array.hs
- asterius/test/cloudflare/cloudflare.hs
- asterius/test/jsffi/AsteriusPrim.hs
- asterius/test/jsffi/jsffi.hs
- asterius/test/parsec/parsec.hs
- asterius/test/rts/FFI.hs
- asterius/test/rts/ForkIO.hs
- asterius/test/rts/MVar.hs
- asterius/test/rts/ThreadDelay.hs
- asterius/test/rtsapi/rtsapi.hs
- asterius/test/teletype/teletype.hs
- asterius/test/text/text.hs
- asterius/test/todomvc/WebAPI.hs
- docs/jsffi.md
- ghc-toolkit/boot-libs/asterius-prelude/src/Asterius/Aeson.hs
- ghc-toolkit/boot-libs/asterius-prelude/src/Asterius/UTF8.hs
- ghc-toolkit/boot-libs/base/Asterius/Prim.hs
- ghc-toolkit/boot-libs/base/Asterius/Types.hs
Closes #411 
We used to use `${i}` to represent the `i`-th argument in the JSFFI source text. Now we switch to `$i` to improve the syntax. Benefits:
* `$i` is a proper JavaScript identifier, no more need for a hacky custom lexer/parser.
* Fixed the templated literals in the source text.
* Got rid of the source text lexer based on `parsec`. We can now emit the source text directly as a vanilla JavaScript expression's source code.
* More closely matches GHCJS import source text syntax.
* Fewer keystrokes.
It's a breaking change, but better break earlier than later! Here's a tip on fixing broken code and documentation: grep for `${1}`, replace with `$1`, increment and repeat. Should be pretty easy.
> Change JSFFI import syntax

- asterius/src/Asterius/GHCi/Internals.hs
This PR forces V8 to use the Ignition interpreter when running WebAssembly code of TH splices. This should make TH compilation faster in general, since TH splice code is short-lived and TurboFan compilation is quite an overhead when the linked splice turns out to be large.
> Enable --wasm-interpret-all for TH splices

- asterius/rts/rts.exports.mjs
- asterius/rts/rts.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Builtins/Exports.hs
- asterius/src/Asterius/Foreign/DsForeign.hs
- asterius/src/Asterius/Foreign/ExportStatic.hs
- asterius/src/Asterius/Foreign/Internals.hs
- asterius/src/Asterius/Foreign/TcForeign.hs
- ghc-toolkit/boot-libs/base/Asterius/Prim.hs
- ghc-toolkit/boot-libs/base/Asterius/Types/JSFunction.hs
Closes #294. Finally.
This PR implements the `foreign import javascript "wrapper"` syntax for exporting arbitrary Haskell function closures to JavaScript callbacks. Example:
```haskell
type Fun = JSVal -> IO JSVal
foreign import javascript "wrapper" mk_Fun_callback :: Fun -> IO JSFunction
```
We can then use `mk_Fun_callback` to convert Haskell closures of type `Fun` to a JavaScript callback at runtime. It's an async function that resolves to a `JSVal` eventually. The callback may call into Haskell again.
When the callback is no longer needed, call `Asterius.Types.freeHaskellCallback` on the `JSFunction`. This will free the callback's own `JSVal` as well as the Haskell closure's `StablePtr`.
Our FFI story is vastly improved now. The previous `makeHaskellCallback*` family of functions will …
> foreign import javascript "wrapper" support

- ghc-toolkit/boot-libs/asterius-prelude/src/Asterius/Aeson.hs
- ghc-toolkit/boot-libs/asterius-prelude/src/Asterius/UTF8.hs
Following recent PRs related to `Asterius.*` refactorings, this PR improves `Asterius.Aeson`:
* We now use the `__asterius_jsffi.exposeMemory` interface directly when marshaling between `JSString`s and UTF-8 encoded `ByteString`s.
* The intermediate `JSVal`s are now freed immediately.
* Added a `jsonFromJSVal'` variant which returns the successfully decoded result type, and throws if decoding fails.
> Slight improvements in `Asterius.Aeson`

- .devcontainer/build.sh
- asterius/app/Setup-ghc-prim.hs
- asterius/app/ahc-boot.hs
- asterius/boot.sh
- asterius/package.yaml
- asterius/src/Asterius/Boot.hs
- asterius/src/Asterius/BuildInfo.hs
- utils/reboot.sh
* The `ASTERIUS_BUILD_OPTIONS` and `ASTERIUS_INSTALL_OPTIONS` options are removed. The only usage previously was specifying `-jN` to speed up single-package building, but that was not the bottleneck and package-level parallelism is good enough.
* We no longer build the `Setup` executables for `Simple` and `Configure` packages; `cabal` has an undocumented `act-as-setup` feature which includes built-in support of these two. As for `ghc-prim`, maybe we can compile the `Setup` executable as an `executable` target of either `ghc-toolkit` or `asterius` and avoid relying on the host `ghc` in `boot.sh`.
> Simplify the booting process

- stack.yaml
#460 introduced a hidden regression previously fixed by #394. This is a quick "fix" (by making the `node` process `SIGKILL`ing itself to avoid hanging) for now, but a more proper solution needs much, much more writing to even explain what had been going wrong in those regressions in the first place, so...leaving that to the future me.
> Bump inline-js revision to fix #394 regression

- base.Dockerfile
- dev.Dockerfile
- stackage.Dockerfile
This PR strips the compiled profile-flavour libs from the base image to further reduce image size. The prebuilt GHC bindists come with profile libs, but the profile libs aren't used in the prebuilt images.
> Strip prof libs from base image

- base.Dockerfile
#509 broke the util scripts building `asterius:base` on my aws instance. Lesson: `rm` can reject with "too many arguments", always use `-delete` of `find` when deleting files conforming to a certain pattern.
> Fix base image

- asterius/rts/rts.scheduler.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Ld.hs
This PR enables user Haskell code to handle `JSException`s even when they are thrown synchronously, either in some piece of `foreign import javascript unsafe` code, or from the runtime itself (e.g. some `TextDecoder` error or something).
IMHO this is a really huge improvement over simply crashing and leaving the thread state in an inconsistent zombie state. It's a good first step towards proper crash semantics of the whole runtime and user code. In our future work, different kinds of crashes should be handled in different manners:
* Runtime crashes which are unrecoverable. These crashes make the whole runtime state inconsistent and no Haskell execution may take place from there. We should immediately reject all pending Haskell thread `Promise`s, do some logging, probably detangling some …
> Enable Haskell code to recover from synchronous JavaScript exceptions

- asterius/rts/rts.mjs
We import `Math` to support certain Cmm instructions like `MO_F64_Sin`. Back in the early days, directly importing `Math` would make V8 crash, so we had to implement eta-expanded wrapper functions for every `Math` function we import. It's not the case anymore since `--wasm-math-intrinsics` works properly and is on by default. Also checked manually that this doesn't break SpiderMonkey.
> import Math directly since --wasm-math-intrinsics is now default

- asterius/src/Asterius/Backends/Binaryen.hs
- asterius/src/Asterius/GHCi/Internals.hs
- asterius/src/Asterius/JSRun/NonMain.hs
- asterius/src/Asterius/Main.hs
- asterius/test/ghc-testsuite.hs
- asterius/test/nomain.hs
Closes #266. Also enables tail calls in the TH runner and `ghc-testsuite`.
> Enable generating tail call opcodes in the `binaryen` backend

- ghc-toolkit/ghc-libdir/include/rts/storage/Block.h
This PR fixes the Cmm macro `Bdescr` which computes the address of the block descriptor given a block address. Its definition is different from GHC's one (due to the different usage of blocks/mblocks) and follows closely the definition in the RTS (`GC.bdescr`).
In order implement Bdescr, it was necessary to port also the C macros `FIRST_BDESCR`, `BLOCK_ROUND_UP`, `FIRST_BLOCK_OFF` to the Cmm world.
> Fix Bdescr Cmm macro

- asterius/src/Asterius/Boot.hs
- asterius/src/Asterius/FrontendPlugin.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/FrontendPlugin.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Orphans/Show.hs
This PR uses the `unsafeGlobalDynFlags` in GHC API for the orphan `Show` instances and replaces the previous `dynFlagsRef`. May help plug a bit of leak here.
> Get rid of custom global `DynFlags`

- asterius/rts/rts.mjs
- asterius/src/Asterius/GHCi/Internals.hs
- asterius/src/Asterius/JSRun/Main.hs
- asterius/src/Asterius/Main.hs
- asterius/test/cloudflare/cloudflare.mjs
- asterius/test/ghc-testsuite.hs
- asterius/test/jsffi/jsffi.mjs
- asterius/test/nomain.hs
- asterius/test/rtsapi/rtsapi.mjs
This PR gets rid of the need of calling `i.exports.hs_init()` explicitly before calling any exported Haskell functions in JavaScript; it's called by the runtime automatically. After `newAsteriusInstance()` resolves with the resulting instance object, all runtime state is already initialized and it's possible to call exported functions by then.
> Automatically call hs_init() before newAsteriusInstance() resolves

- asterius/rts/rts.exports.mjs
- asterius/rts/rts.mjs
- asterius/src/Asterius/Builtins/Exports.hs
- asterius/src/Asterius/Foreign/DsForeign.hs
- asterius/src/Asterius/Foreign/TcForeign.hs
This PR is a further improvement of #502. We already support using the `foreign import javascript "wrapper"` syntax to dynamically export a Haskell function closure to JavaScript; this PR implements the `foreign import javascript "wrapper oneshot"` syntax to dynamically export a one-shot Haskell function closure.
When an exported one-shot Haskell function is called in JavaScript, after the relevant Haskell thread executes to complete, the Haskell function's `JSVal` and `StablePtr` references will be freed automatically.
Exporting Haskell functions that are called only once should be a pretty common use case. This PR optimizes for this case and users don't need to manually call `freeHaskellCallback` explicitly for such functions. Although it's possible to use `fixIO` to implement the …
> Support exporting one-shot Haskell function closures dynamically

- asterius/src/Asterius/CodeGen.hs
- asterius/src/Asterius/EDSL.hs
Until now, the `Asterius.CodeGen.marshalCmmPrimCall` would barf (generate a run-time error) if given an atomic `CallishMachOp` [1].
This PR implements code generation for these operations, by translating them non-atomically. Since currently there is no multithreading, this should suffice for now (we might want to revisit this in the future).
[1] That is, one of `AtomicRMW AMO_Add`, `AtomicRMW AMO_Sub`, `AtomicRMW AMO_And`, `AtomicRMW AMO_Nand`, `AtomicRMW AMO_Or`, `AtomicRMW AMO_Xor`, `MO_AtomicRead`, `MO_AtomicWrite`, or `MO_Cmpxchg`.
> Extend Asterius.CodeGen to marshal atomic operations

- asterius/src/Asterius/Backends/Binaryen.hs
Refactor Asterius.Backends.Binaryen to use a reader monad instead of manually passing all parameters (addresses https://github.com/tweag/asterius/issues/515). The patch does not seem to reduce the size of the file, but hopefully will do so in the future.
> Minor improvements in Asterius.Backends.Binaryen

- asterius/rts/rts.gc.mjs
During a garbage collection, "scavenging" a closure means traversing it to replace each pointer it contains with a pointer to a copied object. The current GC algorithm maintains a list `GC.workList` where closures are enqueued after evacuation, and from where they are dequeued for scavenging afterwards. However, allocating and enqueuing a new JS entry for each Asterius closure looks inefficient, and actually unnecessary. One may instead use directly the "to-space", i.e. the MBlocks allocated during GC for evacuating live closures. It suffices to scan the to-space sequentially, scavenging all the closures that are found.
This PR removes the list `GC.workList` of closures to be scavenged, replacing it with a list `GC.blocksToScavenge` that contains the addresses of the MBlocks in the …
> Scavenging: use the to-space instead of GC.workList

- asterius/src/Asterius/Builtins.hs
This PR addresses https://github.com/tweag/asterius/issues/331.
> Make use of precomputed `Int` and `Char` closures in the runtime

- asterius/rts/rts.constants.mjs
- asterius/rts/rts.gc.mjs
- asterius/rts/rts.heapalloc.mjs
- asterius/src/Asterius/JSGen/Constants.hs
- ghc-toolkit/cbits/ghc_constants.c
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Constants.hs
This PR is a prerequisite for generational GC #455, and it basically introduces generations in the RTS `HeapAlloc` module.
- It adds the new constant `offset_bdescr_gen_no` to read/write generation numbers of MBlocks;
- It adds to `HeapAlloc` the new attribute `generations` which is an array containing the addresses of the block descriptors of the pools for each generation;
- It adds the new method `setGenerationNo` which sets the current unpinned pool to the desired generation, also allocating a new MBlock within that generation if necessary;
- It adds optional arguments to various functions (`hpAlloc`, `allocMegaGroup`, `handleLiveness`), so to handle uniformly pinned/unpinned blocks and generation numbers.
> Basic generational machinery in HeapAlloc

- asterius/src/Asterius/TypeInfer.hs
#534 introduced a hidden regression for the `wasm-toolkit` backend. `wasm-toolkit` relies on a type inference function; the type inference doesn't implement a full inference for all the Asterius IR, and assumes the shape of `Expression`s passed to it. We add one particular case to fix the `wasm-toolkit` test for now, but in the longer term we should either fix the inference or drop it.
> Fix wasm-toolkit regression

- asterius/src/Asterius/Internals/MagicNumber.hs
- asterius/src/Asterius/Main.hs
- asterius/src/Asterius/Resolve.hs
- asterius/src/Asterius/TypeInfer.hs
This patch adjusts the linker to leave the first 1KB memory space empty, and enables the `--low-memory-unused` flag (addressing https://github.com/tweag/asterius/issues/532).
> Unconditionally set --low-memory-unused

- base.Dockerfile
- dev.Dockerfile
Previously we install `nodejs` from the apt repositories maintained by `nodesource`. This PR moves to use `nvm` to manage `node`. This is convenient when we'd like to quickly switch between multiple `node` versions and see whether our generated code (plus the TH runner) still functions properly. Additionally, the `node` version is pinned in the build scripts for improved reproducibility.
The docker images have added `~/.nvm/bin` as a `PATH` entry, so `node`/`npm` is available when the images are run without an interactive `bash` session. `~/.nvm/bin` is a symlink that points to the `bin` directory of the installed `node` version when the image is built. When using the image interactively later, it's possible to simply use `nvm` commands to switch `node` versions.
> Use nvm for managing node installation

- asterius/src/Asterius/TypeInfer.hs
Function `infer` in `Asterius.TypeInfer` has been partial, barfing for unhandled cases. This gave rise to regressions such as the one addressed by https://github.com/tweag/asterius/pull/536. This PR extends `infer` so that it can deal with all possible `Expression` forms properly.
> [WIP] Fix type inference for Asterius.Types.Expression

- base.Dockerfile
- dev.Dockerfile
#571 introduced a hidden regression in the prebuilt images; since we no longer needed to compile C++, we removed `g++`, but `libstdc++-9-dev` has been accidentally removed as well, breaking the `binaryen` package configuration. This PR fixes the problem.
> Add missing libstdc++-9-dev in the prebuilt images

- asterius/rts/rts.exception.mjs
Closes #580. When `updateThunk()` throws, `raiseExceptionHelper()` catches it and implements fallback blackholing logic, to allow the rest of the stack unwinding logic to move on. Compared to proper `updateThunk`, the fallback blackholing logic doesn't take the thread blocking queue of that thunk into account. This should fix the problem of "exported Haskell function's exception doesn't propagate to the `Promise` rejection".
Note that this is a mitigation of #579, not a complete fix; why `updateThunk` assertion fails in the first place will need more investigation.
> Fallback blackholing logic when updateThunk() throws

- base.Dockerfile
- dev.Dockerfile
The docker image builders are reporting build failures `Not cryptographic hash found for Hackage package`. Running a separate `stack update` pass before any build command solves the issue for now.
> Misc fixes

- .buildkite/pipeline.yml
- lts-profile.sh
This PR speeds up the `asterius-profile` job by passing the `-j` flag to `ghc` when building `Cabal`.
> Speed up the `asterius-profile` job

- asterius/src/Asterius/Types.hs
To fix the build failure that https://github.com/tweag/asterius/pull/595 introduced.
> Re-add Asterius.Binary.Orphans import

- asterius/test/nomain/NoMain.hs
- asterius/test/teletype/teletype.hs
- asterius/test/todomvc/WebAPI.hs
- docs/jsffi.md
- ghc-toolkit/boot-libs/asterius-prelude/src/Asterius/ByteString.hs
For the convenience of the TH runner.
> Remove IO from types of ByteString/JSUint8Array conversion functions

- .buildkite/profile.sh
- asterius/package.yaml
This PR changes the default rtsopts we build/profile the `asteirus` executables. This also solves the issue of built-in "GC" cost center occupying the majority of the time usage.
> Change the default rtsopts for `asterius` executables

- asterius/src/Asterius/JSRun/NonMain.hs
- lts.sh
This PR flips on the YOLO mode flag for the TH runner. Combined with #600, this enables the `singletons` package to build (and potentially others as well).
> Use YOLO mode for TH runner

- asterius/rts/rts.memory.mjs
- asterius/rts/rts.mjs
* The initial memory size is no less than `gcThreshold` or `staticMBlocks + 2`. This avoids immediate linear memory growth when initializing the heap allocator.
* When the `getMBlocks` method needs to actually grow the memory, it grows the memory and then recalls itself. We used to immediately return, using the starting point of the extended memory as the allocated space, but this may cause fragmentation (e.g. 1 free mblock left, but 2 is being allocated)
* Fixed incorrect comment in `getMBlocks`.
* The `grow` method no longer returns the previous page count since it's not used. Also, it now updates `this.capacity` as well.
* The `buffer` accessor is removed since it's barely used.
> Misc mblock allocator improvements

- asterius/rts/rts.memory.mjs
- asterius/src/Asterius/GHCi/Internals.hs
Following #607. This fixes the building of `singletons`.
> Only double the linear memory size when it's below 1024M

- ghc-toolkit/boot-libs/asterius-prelude/src/Asterius/ByteString.hs
The new `lazyByteStringToJSUint8Array` function is more efficient than the approach of converting to strict `ByteString`s first, since it operates on the underlying chunks directly.
> Support converting lazy ByteString to JSUint8Array

- profile.Dockerfile
Following #619. Recent toolchain update additionally requires `g++` and `python3` (as build-time transitive dependencies of `npm-utils`).
> Fix the profile job

- asterius/src/Asterius/NFData/TH.hs
- asterius/src/Asterius/Resolve.hs
- asterius/src/Asterius/Types.hs
- asterius/src/Asterius/Types/EntitySymbol.hs
- asterius/src/Asterius/Types/SymbolMap.hs
- asterius/src/Asterius/Types/SymbolSet.hs
* Add `NFData` instances for most datatypes in `Asterius.Types`, and
* Utilize the new `NFData` instances to fully evaluate the shrinked `AsteriusModule` produced by `Asterius.Resolve.linkStart`.
After this PR is merged, we should be able to do a little better, by parallelizing `AsteriusModule`s evaluation (see https://github.com/tweag/asterius/issues/621).
> [WIP] NFData Instance for AsteriusModule

- asterius/app/ahc-ld.hs
Closes #623.
This PR allows `-threaded` to be added to `ghc-options` of executable targets. Since we don't have a threaded flavor of the runtime, the flag is a no-op at link-time.
> Allow linking executables with -threaded

- asterius/rts/rts.exception.mjs
- asterius/src/Asterius/Boot.hs
- ghc-toolkit/boot-libs/rts/StgStdThunks.cmm
Closes #627, #579. We also revert the workaround in #581 since it's no longer needed.
> Enforce eager blackholing in rts

- docs/ahc-link.md
- docs/jsffi.md
- docs/overview.md
- docs/rts-api.md
Since #524 we simplified our RTS API by automatically calling `hs_init()` when the asterius instance object is initialized. Users should not call `hs_init()` in their own code; calling it twice results in undefined behavior. This PR corrects the relevant documentation.
> Remove legacy documentation about hs_init

- .buildkite/test.sh
- asterius/package.yaml
- asterius/rts/browser/default.mjs
- asterius/rts/node/default.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Builtins/Env.hs
- asterius/test/argv.hs
- asterius/test/argv/argv.hs
Closes #634.
This PR fixes `getArgs` for `node`. Say we compile `test.hs` and run `node test.mjs extra flags`, `getArgs` will properly return `["extra", "flags"]`.
The current implementation is just enough to support #640. Limitations compared to native `getArgs`:
* No support for `setProgArgv`.
* Total size of arguments must not exceed 1024 bytes.
* No handling for `+RTS ...` flags. See https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-8.8/rts/RtsFlags.c#L612 for complete logic to handle them, which IMO is an unnecessary complexity to add for now.
* No support for `getFullArgs`.
> Fix `getArgs` support for node

- asterius/src/Asterius/GHCi/Internals.hs
Following #633, another V8 runtime option tuning for TH splices that result in minor overall speedups.
> Omit V8 bounds checks & stack checks when running TH splices

- asterius/rts/browser/default.mjs
- asterius/rts/node/default.mjs
- asterius/src/Asterius/Builtins/Posix.hs
> Implement __hscore_ftruncate

- asterius/app/ahc-ar.hs
- asterius/app/ahc-cabal.hs
- asterius/boot.sh
- asterius/package.yaml
- asterius/src/Asterius/Ar.hs
- asterius/src/Asterius/Binary/ByteString.hs
- asterius/src/Asterius/Boot.hs
- asterius/src/Asterius/BuildInfo.hs
> WIP Implement ahc-ar

- .buildkite/pipeline.yml
This PR removes `asterius-profile` from regular CI jobs. The profile job will be migrated to a standalone branch to be run on buildkite or github actions.
> Remove asterius-profile from regular CI jobs

- asterius/app/ahc-ar.hs
When implementing `ahc-ar` (PR https://github.com/tweag/asterius/pull/663), we didn't expect that  filenames with quotes, spaces, etc. would appear in `.rsp` files, but after all they do (https://github.com/tweag/asterius/issues/670). This PR reverses the effects of [escapeResponseFileArg](https://github.com/haskell/cabal/blob/dde6255a4e6b531c0567bc499840d11ead9d885b/Cabal/Distribution/Simple/Program/ResponseFile.hs#L48) and closes https://github.com/tweag/asterius/issues/670.
> Un-escape .rsp contents to reverse the effects of Cabal's escapeResponseFileArg

- .github/workflows/pipeline.yml
This PR adds builds of the `base`/`dev` images to GitHub Actions, since their build times are short enough to be contained in a regular CI build. The benefits are:
* We can catch regressions in the image build scripts when we make architectural changes
* People can use the artifacts directly as prebuilt binaries. Better tracking of revisions compared to docker hub.
The `stackage` image needs to be built on BuildKite for now.
> Build base/dev images on GitHub Actions

- asterius/app/ahc-cabal.hs
- asterius/cabal/config
- asterius/package.yaml
- base.Dockerfile
- stackage.Dockerfile
* We now use `~/.ahc-cabal` as a standalone `cabal` root directory. This avoids clashes with `~/.cabal`, and clears the main obstacle of #638
* The extra `cabal` config entries are included in the `cabal/config` file in tree, instead of hard-coding in `ahc-cabal.hs`. At run-time, we add the `program-locations` section and write it to `~/.ahc-cabal/config`. One downside: users can't customize `ahc-cabal` via `~/.ahc-cabal/config` since it always gets rewritten, but it's doubtful if there's really such a use case lol
* `ahc-cabal` now uses FP Complete's Hackage mirror by default and enables `hackage-security` verification.
> ahc-cabal improvement

- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Builtins/Math.hs
This PR adds C standard library bindings to the following triangular functions: `cos`, `tan`, `sinh`, `cosh`, `tanh`, `asin`, `acos`, `atan`, `log`, and `exp`.
Closes https://github.com/tweag/asterius/issues/673.
> Implement Asterius.Builtins.Math

- asterius/src/Asterius/Types.hs
Was:
```
/Users/ggreif/asterius/asterius/src/Asterius/Types.hs:62:1: warning: [-Wunused-imports]
The import of ‘Control.DeepSeq’ is redundant
except perhaps to import instances from ‘Control.DeepSeq’
To import instances alone, use: import Control.DeepSeq()
|        
62 | import Control.DeepSeq
| ^^^^^^^^^^^^^^^^^^^^^^
```
> Remove warning

- base.Dockerfile
- dev.Dockerfile
Solves image build regressions in #688.
> Set npm `unsafe-perm` flag to true in image build scripts

- .github/workflows/pipeline.yml
Following #689, apply `zstd` compression to image artifacts on CI. GitHub's `zip` archives are still GiB-sized when serving the raw tarballs.
> Apply compression to image CI artifacts

- asterius/src/Asterius/CodeGen.hs
- asterius/src/Asterius/Passes/GCSections.hs
- asterius/src/Asterius/Types.hs
This PR removes `staticsErrorMap` from `AsteriusModule`. Though small, this change eliminates data dependencies in `gcSections`, and thus simplifies the development of https://github.com/tweag/asterius/pull/666.
> Remove (expected obsolete) staticsErrorMap

- .github/workflows/pipeline.yml
The image build jobs on CI has been failing with:
```
systemd cgroup flag passed, but systemd support for managing cgroups is not available
```
For now, we need to manually specify `cgroup_manager="cgroupfs"` in the user-level `libpod.conf` to fix this.
> Fix podman on CI

- asterius/src/Asterius/Passes/GCSections.hs
- asterius/src/Asterius/Types/EntitySymbol.hs
Being able to partition `gcSections` into two separate phases without problems (all tests must pass and there should be no performance regressions) is a great step in the right direction. If this PR works as expected, we shall edit the second phase (module filtering/creation from disk) afterwards in a separate PR, instead of doing all at once (PR #666).
> Refactor gcSections to resolve symbols first and gc after

- .github/workflows/setup-deps.sh
- base.Dockerfile
- dev.Dockerfile
- docs/building.md
- stack-profile.yaml
- stack.yaml
Close #699. Use `binaryen-0.0.2.0` which works with `version_94`.
> Binaryen update

- asterius/src/Asterius/Monoid/TH.hs
- asterius/src/Asterius/Semigroup/TH.hs
- asterius/src/Asterius/Types.hs
By "trivial" we mean instances for types with a single data constructor, where `mappend` simply `mappend`s the fields element-wise.
> Use TH for generating trivial Semigroup and Monoid instances

- asterius/src/Asterius/Resolve.hs
- asterius/src/Asterius/Types/LinkReport.hs
~~Though lawful, these~~ These instances (the `Semigroup` one in particular) assume that `tableSlots` and `staticMBlocks` will be set correctly externally, which is weird and could easily get them out-of-sync. Fortunately, they don't seem to be used anywhere (the only place that seems to use them in `linkStart` sets all the fields explicitly anyway).
> Delete law-violating obsolete Semigroup/Monoid instances for LinkReport

- asterius/src/Asterius/Ar.hs
Following PR https://github.com/tweag/asterius/pull/678, we can simplify archive files and their treatment even more:
* There is no need for keeping track of the names of the object files the archive file contains; we never use them, and they are not even accurate (`takeFileName` drops most of the path).
* If there is no need for names, there is definitely no need for creating and parsing the initial entry containing all long filenames.
* In fact, all other metadata is also set to defaults; there is no point in reading these either.
So, this PR strips treatment of archive files down to the bare minimum:
* Drops the filename table entry
* Drops fine deserialization of metadata
* Represents archive files as just the list of the content of the binary files they contain.
It would have been …
> Simplify treatment of archive files

- .github/workflows/pipeline.yml
- asterius/src/Asterius/Internals/Timeout.hs
- asterius/src/Asterius/JSRun/Main.hs
- asterius/test/ghc-testsuite.hs
`ghc-testsuite` has regressed (~600 failures); the regressed tests would produce an empty `stdout`/`stderr`, and the root cause is the `main` `IO` action in compiled modules haven't been fully executed and returned before we attempt to read `stdout`/`stderr`.
> Fix ghc-testsuite major regression

- asterius/boot.sh
- asterius/src/Asterius/Boot.hs
- ghc-toolkit/ghc-libdir/settings
This PR makes `-DASTERIUS` a wired-in CPP flag for `ahc`. Asterius users shall be able to use the `ASTERIUS` CPP macro to determine whether the current module is being compiled by asterius, without specifying additional flags to `ahc-cabal`, `ahc-link`, etc. Relevant: #722
> Make -DASTERIUS a wired-in CPP flag

- asterius/src/Asterius/CodeGen/Droppable.hs
Fixes support for the `clock` package, closes #730. See #452 for more explanation.
> Fix clock support

- asterius/rts/rts.eventlog.mjs
- asterius/rts/rts.mjs
AFAICT there is no real need for EventLogManager to depend on the symbol table, and I didn't find any usage of it currently. I believe we should be able to drop this dependency.
> Remove obsolete EventLogManager dependency on symbolTable

- .github/workflows/pipeline.yml
- README.md
- asterius/test/todomvc/index.html
- asterius/test/todomvc/package.json
Demos are now built by BuildKite using the latest docker image on the `buildkite-examples` branch. The artifacts are uploaded to our S3 bucket, and the regular CI `docs` job fetch them and deploy them to netlify. The links in `README` is corrected.
Also includes a minor fix for `todomvc`.
> Fix demo links

- asterius/rts/rts.exports.mjs
- asterius/test/todomvc/WebAPI.hs
When a Haskell function with arity `n` is exported to JavaScript, previously, it must also be called with exactly `n` arguments, otherwise a runtime error will be thrown. This PR lessens the check and allows more than `n` arguments to be passed. The first `n` arguments will be passed to Haskell, and the rest will be ignored.
The rationale for this change: fix an undiscovered break in the `todomvc` example. We used to export a `IO ()` continuation as an event handler, but in JavaScript, all event handlers are passed with an event object parameter. The correct behavior should be simply ignoring that parameter; but after #501 this has been silently broken.
Also includes another fix of `todomvc` due to `JSVal` use-after-free caused by laziness.
> Allow exported Haskell functions to be called with redundant arguments

- asterius/cabal/config
- asterius/src/Asterius/Boot.hs
- asterius/src/Asterius/Internals.hs
This PR enables relocatable packages for `ahc-cabal`. Benefits:
* The boot package database will become relocatable. It'll be easy to implement support for switching between multiple boot package databases at runtime, and we can provide the prebuilt stackage packages as a tarball in addition to a full-fledged image. This will shorten the dev feedback cycle considerably.
* For V1-style builds, the result of `getDataDir` will no longer return a hard-coded absolute path; it'll compute the path prefix based on the `getExecutablePath` return value. This makes it possible to support packages which use `data-dirs` in the browser, provided we can transitively collect the data files and serve them via a virtual FS. (V2-style builds don't support this yet)
> Enable relocatable packages for `ahc-cabal`

- asterius/src/Asterius/Passes/DataSymbolTable.hs
- asterius/src/Asterius/Resolve.hs
This PR simplifies the implementation of `makeMemory`, which creates the `DataSegment`s from `AsteriusStatics` (and computes the offset of each segment). More specifically,
* We get rid of a small optimization that over-complicated the code (merging adjacent data segments into one, if possible). Now each `AsteriusStatic` gives rise to its own `DataSegment` (uninitialized statics do not give rise to data segments, still).
* We compute the data segment offsets left-to-right, as opposed to the previous approach that computed the offsets by subtracting the length of each segment from the offset at its end.
* `makeMemory` no longer computes `initial_pages`; this task is delegated to `resolveAsteriusModule`, where it belongs. This change also eliminates two unnecessary calls to `fromIntegral`.
> Simplifications in Asterius.Passes.DataSymbolTable

- .github/workflows/pipeline.yml
Since the default backend is binaryend, the tests in `.github/workflows/pipeline.yml` that have no explicit backend are basically executed the same way by both `test-binaryen` and `test-wasm-toolkit`. Instead of running the same test twice, we might as well test the `wasm-toolkit` backend a little more.
> Remove duplication between test-binaryen and test-wasm-toolkit

- .github/workflows/pipeline.yml
- asterius/package.yaml
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Builtins/Endianness.hs
- asterius/src/Asterius/CodeGen.hs
- asterius/test/endianness.hs
- asterius/test/endianness/endianness.hs
Closes #756. This PR
Adds `Asterius.Builtins.Endianness` with implementations for
* `hs_bswap16`, `hs_bswap32`, and `hs_bswap64`.
* `htonl`, `htons`, `ntohl`, and `ntohs`, based on the `hs_bswap*` functions. Wasm uses little-endian while network order is big-endian; converting from one to the other simply means byte-swapping.
Also
* Adds a small unit test (`endianness`).
* Implements translations for [`CallishMachOp`](https://haskell-code-explorer.mfix.io/package/ghc-8.6.5/show/cmm/CmmMachOp.hs#L523) `MO_BSwap`, using `hs_bswap16`, `hs_bswap32`, and `hs_bswap64`.
* Adds a few comments about remaining unimplemented translations in `Asterius.CodeGen`.
> Wasm implementations of hs_bswap and ntohs functions

- .github/workflows/pipeline.yml
- asterius/app/ahc-cabal.hs
Closes #755, also adds a simple v2 build test in `test-cabal` CI job to prevent regression.
Why on earth does the `with-compiler` cabal config field behaves differently from `ghc-location`??? And the former is marked as deprecated, but works, while the latter one doesn't???
> Fix ahc-dist broken when handling ahc-cabal v2 build output

- asterius/rts/rts.symtable.mjs
- asterius/src/Asterius/GHCi/Internals.hs
When we handle the `RunTH` message and kicks off the evaluation of a splice's code, we fork a thread as a watchdog to catch potential `EvalError` in the relevant thunk. In case of such an error, we log it to `stderr` and kill the `Session`, which shall make `ahc` crash instead of infinitely hanging.
The real cause of hanging before: `readIServ` may wait for data on the iserv pipe, so when TH runner errors, the `node` process may still be alive, thus `readIServ` blocks.
Also adds another minor runtime bugfix: symbol table should check for invalid symbols instead of silently returning `undefined`.
> Prevent TH runner errors from hanging the ahc process

- asterius/src/Asterius/Backends/Binaryen.hs
- asterius/src/Asterius/Backends/WasmToolkit.hs
I found the culprit of https://github.com/tweag/asterius/issues/757: https://github.com/tweag/asterius/pull/743 looks up symbols in the wrong symbol table I believe. Both in `WasmToolkit` and `Binaryen`. It fails to find the corresponding static (cause it wrongly looks into the `func_sym_map` instead of the `ss_sym_map`), so it falls back to emitting a plain `unreachable`. This PR addresses this regression.
I still think that it'd be nice to switch to the new translation for `Barf`s as described in https://github.com/tweag/asterius/issues/757 but for now this patch should give us the expected behavior.
> Fix barf regression

- asterius/src/Asterius/Backends/Binaryen.hs
- asterius/src/Asterius/Backends/WasmToolkit.hs
- asterius/src/Asterius/Passes/FunctionSymbolTable.hs
- asterius/src/Asterius/Types.hs
Binaryen allows for the table offset in a function table to be an arbitrary expression, but until now the Asterius IR would only allow integers to be used here. This PR lifts this restriction. This change should allow us to change the offset dynamically in the future.
Factored out from https://github.com/tweag/asterius/pull/750.
> Generalize tableOffset in FunctionTable

- asterius/src/Asterius/Backends/Binaryen.hs
- asterius/src/Asterius/Backends/WasmToolkit.hs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/EDSL.hs
Until now `__asterius_pc` has been a static (data segment). This means that `__asterius_pc` should be adjusted as well when #750 lands, which complicates the backends. Instead, this PR turns it into a global which can be referred to by name, thus avoiding this problem altogether.
Factored out from #750.
> Turn __asterius_pc into a global

- asterius/rts/rts.mjs
- asterius/rts/rts.symtable.mjs
Instead of storing the `table_base` and `memory_base` values into the symbol table in the rts, after this PR there is only a single source for these values: ` __asterius_table_base.value` and `__asterius_memory_base.value`, respectively. This is more robust and shorter.
Factored out from #750.
> Remove getTableBase and getMemoryBase

- wasm-toolkit/test/wasm-toolkit-codec.hs
Closes #551 by setting the number of tests for `wasm-toolkit/test/wasm-toolkit-codec.hs` to a reasonable number. Now `stack test wasm-toolkit` terminates just fine.
> Set No of iterations for wasm-toolkit-codec to default (100)

- asterius/rts/rts.mjs
- asterius/rts/rts.symtable.mjs
- asterius/src/Asterius/Backends/Binaryen.hs
- asterius/src/Asterius/Backends/WasmToolkit.hs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Main.hs
Essentially undo the inconsistencies that came with 346275d.
* No mention of base addresses in either Haskell land or JavaScript land; these should really come with #750.
* The symbol tables are treated as symbol tables everywhere; no adding `base` as if they contained offsets.
> Re-establish a consistent view on Offset/Symbol tables

- dev.Dockerfile
- dev.rootless.Dockerfile
This PR adds `xdg-open` to the dev image and sets `BROWSER=echo`. Also contains some refactorings in the rootless dev image script.
> Add xdg-open to the dev image and use a dummy browser

- asterius/src/Asterius/Main.hs
This PR makes `--debug` imply `--optimize-level=0` and `--shrink-level=0`. When working under debug mode, it's sensible to avoid running any `binaryen` passes at all, so to reduce the possibility of codegen bugs. Should also speed up the CI a bit.
> Disable binaryen optimize/shrink passes in debug mode

- .github/workflows/pipeline.yml
- base.Dockerfile
- dev.Dockerfile
- dev.rootless.Dockerfile
Not updating the stackage snapshot this time, since we may switch to a `nixpkgs`-based snapshot generator recently.
* Update `stack` to `2.5.0.1` in the images to address the `casa.fpcomplete.com` timeout problem.
* Update `node` to `14.12.0`
* Update `nvm` to `0.36.0`
* Update `python` to `3.8.6`
> Toolchain update

- asterius/src/Asterius/CodeGen.hs
- asterius/src/Asterius/Passes/DataOffsetTable.hs
We used to align data segments by 16 bytes. It's a simple upper-approximation since on x64 `ReadOnlyData16` requires 16-byte alignment while others require at most 8-byte. Given `ReadOnlyData16` doesn't seem to be actually used in our pipeline, this PR reduces the alignment value to 8 bytes when laying out data segments. This will result in more compact static memory data (even so when #750 lands and `--pic` is enabled).
> Align data segments by 8 bytes instead of 16

- asterius/src/Asterius/Backends/Binaryen.hs
- asterius/src/Asterius/Backends/Binaryen/CheckOverlapDataSegment.hs
Accidentally overlapping data segments cost us a ton of debugging time when working on #729. It's reasonable to make a mandatory pass to prevent future regressions.
> Implement data segment overlap check

- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/CodeGen.hs
- asterius/src/Asterius/EDSL.hs
- asterius/src/Asterius/Internals/Barf.hs
- asterius/src/Asterius/Types.hs
This PR adds a `FFIHint` type that models `ForeignHint` in GHC API, and uses it to annotate argument/result types of C FFI. Since we use the `Call` node for both regular C FFI (as in `foreign import ccall`) and runtime intrinsic calls, this hint is optional and should only exist if the callee is indeed a C function.
Adding type hints is a prerequisite to support calling a C function in the `wasi-sdk` world, since we need to cast between 32/64 bit pointers when marshaling such a call. Without modifying the IR, we would need to use JavaScript wrappers for each such function, which brings too much boilerplate and extra overhead.
> Add optional type hints to C FFI

- .github/workflows/pipeline.yml
- .github/workflows/setup-deps.sh
- base.Dockerfile
- dev.Dockerfile
- dev.rootless.Dockerfile
- docs/building.md
Another prerequisite for #729. We now require `wasi-sdk` to be set up in the user environment, and `WASI_SDK_PATH` is expected to point to its installation path (`/opt/wasi-sdk` when using the official builds). We also set up `wasi-sdk` on CI and our prebuilt images.
> Set up wasi-sdk

- asterius/src/Asterius/Internals/SYB.hs
- asterius/src/Asterius/Passes/FindCCall.hs
- asterius/src/Asterius/Resolve.hs
- asterius/src/Asterius/Types/LinkReport.hs
A part of #729 work:
* Add an SYB-style generic query function `everything`
* Implement a `FindCCall` pass that traverses the IR and looks for ccalls with type hints (which comes from a `foreign import ccall`)
* Add `usedCCalls` to `LinkReport`, and it's populated by all found ccalls *excluding* the ones already present in the wasm world. So if we have a built-in runtime function `func` and it's used by a `foreign import` somewhere, then `func` won't be present in `usedCCalls`. This ensures compatability: the external C world is only used to complement the missing bits, not to overwrite existing stuff.
> Analyze used ccalls in linker output

- asterius/rts/rts.memory.mjs
- asterius/src/Asterius/Builtins.hs
- asterius/src/Asterius/Builtins/Primitive.hs
- asterius/src/Asterius/Builtins/SM.hs
- asterius/src/Asterius/CodeGen.hs
- asterius/src/Asterius/EDSL.hs
- asterius/src/Asterius/EDSL/LibC.hs
- asterius/src/Asterius/JSGen/LibC.hs
We now use memory management functions in `libc` instead of the imported JavaScript functions.
`primitive` related shims are not removed in this PR for now since there's a behavior change that requires debugging.
> Remove legacy memory-related runtime shims

- asterius/rts/rts.exception.mjs
- asterius/src/Asterius/Builtins/Barf.hs
- asterius/src/Asterius/Internals/Barf.hs
- asterius/src/Asterius/Ld.hs
- asterius/src/Asterius/Passes/Tracing.hs
- asterius/src/Asterius/Resolve.hs
* `barf_throw` is renamed to `barf_signal` and takes a boolean flag to indicate whether an exception should be raised.
* When debug mode is on, each function uses `barf_push`/`barf_signal` to emit its function name as a tracing message.
> Cheap tracing pass in debug mode

- asterius/rts/browser/rts.wasi.mjs
- asterius/rts/node/rts.wasi.mjs
- asterius/rts/rts.mjs
- asterius/src/Asterius/Backends/Binaryen.hs
- asterius/src/Asterius/Backends/Binaryen/RunPass.hs
- asterius/src/Asterius/Builtins/Primitive.hs
- asterius/src/Asterius/GHCi/Internals.hs
- asterius/src/Asterius/JSGen/LibC.hs
- asterius/src/Asterius/Main.hs
* For the node runtime, `wasi_snapshot_preview1` now comes from node's own `WASI` implementation. This also implies that wasm bigint integration is now mandatory.
* For the browser runtime, we now include placeholders of all wasi interfaces.
* Redundant export entries which aren't used by the JS runtime are now pruned.
* Fixes `--no-gc-section` test regression on the master branch.
* Fixes `primitive` shims validation error.
Open problem: how do we preserve our special handling of `stdout`/`stderr` once we start using vanilla libc file IO?
> Use node wasi interface & misc other fixes

- asterius/app/ahc-cabal.hs
- asterius/src/Asterius/Boot.hs
This PR enables `hsc2hs --cross-compile` both during booting and later for `ahc-cabal`. `--via-asm` should make it faster, but given `hsc2hs` fails to parse `.s` file of `clang` when targetting `wasm32-wasi`, so not adding that one.
After running a full stackage build, these packages and their dependents fail to compile due to `hsc2hs` features unsupported in cross-compilation mode:
* `blake2-0.3.0`
* `lukko-0.1.1.2`
* `terminal-size-0.3.2.1`
* `unix-bytestring-0.3.7.3`
* `yoga-0.0.0.5`
* `mercury-api-0.1.0.2`
When we later finish all the 32-bit transition, we can propose patches to package upstream that fix their builds again.
> Enable --cross-compile for hsc2hs

- asterius/src/Asterius/JSGen/LibC.hs
Fixes the `clang-11: warning: -Wl,--lto-O3: 'linker' input unused [-Wunused-command-line-argument]` warning.
> Fix clang warning about redundant linker flag

- ghc-toolkit/boot-libs/cabal.config
- utils/gen-pkgs.hs
We don't include `libgmp` in our `wasi-sdk` builds yet, so `gmp`-related flags need to be turned off.
> Fix default cabal flags of bitvec

- asterius/rts/browser/rts.wasi.mjs
- asterius/rts/node/rts.wasi.mjs
We used to use `wasi.wasiImport` directly as the import object for wasi, which is efficient but doesn't allow us to override the behavior of certain syscalls. This PR adds the missing indirection layer. Starting from here we can unify some existing runtime logic (especially filesystem/stdio stuff, pretty chaotic atm)
> wasi: add an indirection layer in import object

- asterius/src/Asterius/CodeGen.hs
- asterius/src/Asterius/FrontendPlugin.hs
- asterius/src/Asterius/GHCi/Internals.hs
- ghc-toolkit/ghc-libdir/settings
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Compiler.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Hooks.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Run.hs
- utils/make-packages.py
This PR is a prerequisite for the `ahc -c` fixing work. One more step towards a less hacky ghc frontend.
* Uses `asterius-8.8-staging` branch which removes legacy `stgCmmHook`/`cmmToRawCmmHook` and adds `codeOutputHook`. `codeOutputHook` is a better way of working with raw Cmm for Haskell/Cmm inputs uniformly.
* Minor fix in the `settings` file since the staging branch is rebased on latest upstream `ghc-8.8` which invalidates our earlier `settings`
> Use updated ghc branch with codeOutputHook

- asterius/cabal/config
- asterius/src/Asterius/Main.hs
- base.Dockerfile
- dev.Dockerfile
- dev.rootless.Dockerfile
* Enable `-O2` by default in `ahc-cabal`/`ahc-link`
* Remove redundant `ahc` arguments in `ahc-link`
> Adjust cabal/ahc flags

- asterius/src/Asterius/Boot.hs
- ghc-toolkit/src/Language/Haskell/GHC/Toolkit/Run.hs
This PR undoes a part of the code cleanup in #821 to fix `diagrams-lib` TH breakage. The root cause of the error is yet to be investigated.
> Workaround diagrams-lib TH breakage

- .github/workflows/pipeline.yml
- asterius/app/ahc-dist.hs
- asterius/app/ahc-link.hs
- asterius/app/ahc-pkg.hs
- asterius/cabal/config
- asterius/ghc-bin-asterius/Main.hs
- asterius/src/Asterius/Boot.hs
* Fix "cannot satisfy -package-id" regression in packages with exe targets by moving our hook initialization logic in `ahc` to a later place.
* Don't cancel the `GHC_`/`HASKELL_` env vars in `ahc`/`ahc-pkg` since `ahc-cabal` may pass these. Do this in `ahc-link`/`ahc-dist` instead since they are likely invoked by `stack exec`.
* Remove `deterministic` related configure flags since we don't need them anyway.
* Add `hlint` to `ahc-cabal` CI test build for this particular case.
> Fix "cannot satisfy -package-id" regression in packages with exe targets

- ghc-toolkit/boot-libs/cabal.config
- utils/make-packages.py
Instead of copying, use hard links when copying files in the materialize script. This is useful when using the materialize script outside the `asterius` repo for hacking on our custom GHC fork; all the local changes in the materialized packages will be picked up by `git` when scanning the `ghc` repo.
> Use hard links in the materialize script

- asterius/rts/rts.stablename.mjs
This PR fixes `StableName#` object allocation: the size is corrected, and they are no longer pinned.
> Fix StableName# object allocation

- asterius/rts/rts.exports.mjs
- asterius/rts/rts.gc.mjs
- asterius/rts/rts.jsval.mjs
- asterius/rts/rts.mjs
- asterius/rts/rts.scheduler.mjs
- asterius/rts/rts.stableptr.mjs
- asterius/src/Asterius/GHCi/Internals.hs
- asterius/src/Asterius/JSFFI.hs
- ghc-toolkit/boot-libs/base/Asterius/Types/JSVal.hs
Following #841, this PR decouples the `JSValManager` from `StablePtrManager` and moves it to a standalone module. Also, the `newJSVal`/`getJSVal`/`freeJSVal` method names now carry a `zh` suffix to emphasize that they operate on *unlifted* `JSVal#` closures instead of lifted `JSVal` closures (which are dealt with `rts_mkJSVal`/`rts_getJSVal`).
> Standalone JSVal manager in the runtime

- asterius/src/Asterius/Ld.hs
- asterius/test/rtsapi/rtsapi.mjs
This PR cleans up the set of predefined root symbols, since the runtime doesn't actually need a lot of these. In the distant future, we should be using ` __attribute__((export_name(<name>)))` of `clang` and get rid of this hack.
> Cleanup predefined root symbols

- asterius/src-types/Asterius/Types.hs
- asterius/src/Asterius/Foreign/SupportedTypes.hs
- asterius/src/Asterius/JSFFI.hs
This PR adds 8/16/32/64-bit sized `FFIValueTypeRep`. This is a prerequisite for unifying our JSFFI runtime type information implementation.
> Add missing sized variants of FFIValueTypeRep
